/* ============================================================
   IntoDay Landing Page — i18n + Language Switcher
   ============================================================ */

const translations = {
    en: {
        flag: '🇬🇧',
        label: 'EN',
        nav_cta: 'Start for free',
        hero_title: 'Keep today’s things and links together',
        hero_sub: 'Use time blocks to hold your day together — tasks, links, places, and notes, all in one place.',
        hero_cta: 'Start for free',
        f1_label: 'Organize by time periods',
        f1_title: 'No need for calendar slots or mental notes',
        f1_desc: 'Small things can easily go into the right time block',
        f2_label: 'Instant access',
        f2_title: 'Every item leads you to the next step',
        f2_desc: 'Easily add links, locations, files, and text – open them anytime in a clearer, more readable form',
        f3_label: 'Keep it simple',
        f3_title: 'Everything for today, all on one page.',
        f3_desc: 'Your day is focused in one place, clear and visible. Everything you need to handle stays right in front of you.',
        uc1_title: 'Work follow-ups',
        uc1_desc: 'Keep handoffs, follow-ups, and post-meeting tasks in one place – not scattered across notes, chats, and to-do lists.',
        uc2_title: 'Between classes and homework',
        uc2_desc: 'Things to submit, materials to read, messages to reply, tasks for later... no exact time needed, just place them in the right part of your day.',
        uc3_title: 'For days that keep shifting',
        uc3_desc: 'Groceries, trips, city walks, or busy multi-tasking days – things can move easily, and your plans stay clear.',
        quote: 'No longer pulled between scattered things and rigid schedules',
        quote_author: 'The IntoDay Philosophy',
        cta_title: 'Starting today, give things a place and give actions an entry!',
        cta_btn: 'Start for free',
        footer_help: 'Help / Feedback',
        footer_privacy: 'Privacy Policy',
        footer_terms: 'Terms of Service',
        footer_copy: '© 2026 IntoDay. All rights reserved.',
        pp_title: 'Privacy Policy of IntoDay',
        pp_effective: 'Effective Date: @2026/3/12',
        pp_intro: 'IntoDay (“we,” “us,” or “our”) respects your privacy. This Privacy Policy explains what information we collect, how we use it, and what choices you have when using IntoDay.',
        pp_desc: 'IntoDay is a tool for organizing tasks, reminders, follow-ups, and small plans into time blocks throughout the day.',
        pp_contact_intro: 'If you have any questions about this Privacy Policy, you can contact us at: contact.intoday@gmail.com',
        pp_s1_title: '1. Who We Are',
        pp_s1_desc: 'IntoDay is the provider of the IntoDay app and related website. If you have questions about privacy or data handling, you can contact us at: contact.intoday@gmail.com',
        pp_s2_title: '2. Information We Collect',
        pp_s2_desc: 'We collect only the information necessary to provide and improve IntoDay.',
        pp_s2_1_title: '2.1 Account Information',
        pp_s2_1_desc: 'If you sign in with Google, we may receive basic account information such as:',
        pp_s2_1_list: '<li>your email address</li><li>your Google account identifier</li><li>your name or profile image, if provided through your login permissions</li>',
        pp_s2_1_meta: 'We use this information to create and manage your account and let you sign in securely.',
        pp_s2_2_title: '2.2 Content You Add to IntoDay',
        pp_s2_2_desc: 'When you use IntoDay, we may store the content you choose to add, such as tasks, reminders, notes, links, locations, file-related references, and other task-related text you enter into the app.',
        pp_s2_2_meta: 'We use this information to provide the core functionality of IntoDay, including displaying, organizing, and syncing your content.',
        pp_s2_3_title: '2.3 Technical and Usage Data',
        pp_s2_3_desc: 'When you use IntoDay, we may automatically collect certain technical information, such as:',
        pp_s2_3_list: '<li>device and browser information</li><li>IP address</li><li>log data</li><li>usage analytics and product interaction data</li>',
        pp_s2_3_meta: 'We use this information to keep the service running securely, understand app performance, fix bugs, and improve the product experience.',
        pp_s3_title: '3. How We Use Your Information',
        pp_s3_desc: 'We use your information to provide and maintain IntoDay, enable secure login, store and display your tasks and content, support syncing and account-related functions, monitor stability, performance, and security, and improve the app over time.',
        pp_s4_title: '4. Third-Party Services We Use',
        pp_s4_desc: 'We use trusted third-party service providers to operate IntoDay.',
        pp_s4_1_title: '4.1 Supabase',
        pp_s4_1_desc: 'We use Supabase for authentication, database, and backend-related services. Supabase may store your account data and the content you add to IntoDay as needed to provide the service.',
        pp_s4_2_title: '4.2 Google Sign-In',
        pp_s4_2_desc: 'If you choose to log in with Google, Google provides the authentication process and may share basic account information with us, depending on the permissions you grant.',
        pp_s4_3_title: '4.3 Vercel',
        pp_s4_3_desc: 'We use Vercel to host and deliver the IntoDay website and web app. Vercel may process technical information such as IP address, browser/device details, and request logs for hosting, delivery, and security purposes.',
        pp_s5_title: '5. How We Share Information',
        pp_s5_desc: 'We do not sell your personal information. We may share your information only with service providers that help us operate IntoDay, when required by law, or when necessary to protect the security, rights, or integrity of IntoDay and its users.',
        pp_s6_title: '6. Data Retention',
        pp_s6_desc: 'We keep your information only for as long as it is needed to provide IntoDay and operate the service. If you delete your account or request deletion, we will make reasonable efforts to delete your personal data within a reasonable period, unless we are required to keep certain information for legal, security, or operational reasons.',
        pp_s7_title: '7. Data Security',
        pp_s7_desc: 'We take reasonable technical and organizational measures to protect your information from unauthorized access, loss, misuse, or disclosure. However, no system is completely secure, and we cannot guarantee absolute security.',
        pp_s8_title: '8. Your Choices and Rights',
        pp_s8_desc: 'Depending on your location, you may have rights regarding your personal data, including the right to access, correct, or request deletion of your data. To make a request, contact us at: contact.intoday@gmail.com',
        pp_s9_title: '9. Children’s Privacy',
        pp_s9_desc: 'IntoDay is not intended for children under the age required by applicable law to use such services without parental consent. We do not knowingly collect personal information from children in violation of applicable law.',
        pp_s10_title: '10. Changes to This Privacy Policy',
        pp_s10_desc: 'We may update this Privacy Policy from time to time. If we make material changes, we will update the “Effective Date” at the top of this page and, where appropriate, provide additional notice.',
        pp_s11_title: '11. Contact',
        pp_s11_desc: 'If you have any questions, feedback, or privacy-related requests, you can contact us at: contact.intoday@gmail.com',
        ts_title: 'Terms of Service of IntoDay',
        ts_effective: 'Effective Date: @2026/3/12',
        ts_intro: 'These Terms of Service (“Terms”) govern your access to and use of IntoDay (“IntoDay,” “we,” “us,” or “our”).',
        ts_agree: 'By accessing or using IntoDay, you agree to these Terms. If you do not agree, please do not use IntoDay.',
        ts_s1_title: '1. About IntoDay',
        ts_s1_desc: 'IntoDay is a tool for organizing tasks, reminders, follow-ups, and small plans into time blocks throughout the day. IntoDay is currently provided as an early-stage product / beta service. Some features may change, be updated, or be removed over time.',
        ts_s2_title: '2. Eligibility',
        ts_s2_desc: 'You may use IntoDay only if you can legally enter into a binding agreement under the laws that apply to you.',
        ts_s3_title: '3. Your Account',
        ts_s3_intro: 'You may sign in to IntoDay using Google authentication. You are responsible for:',
        ts_s3_list: '<li>maintaining the security of your account</li><li>keeping your login credentials safe</li><li>all activity that occurs under your account</li>',
        ts_s3_contact: 'If you believe your account has been accessed without authorization, please contact us at: contact.intoday@gmail.com',
        ts_s4_title: '4. Your Content',
        ts_s4_desc: 'You may add content to IntoDay, including tasks, reminders, notes, links, locations, file-related references, and other text. You retain ownership of the content you submit to IntoDay. You grant us a limited right to store, process, and display your content only as necessary to operate and provide the service. You are responsible for the content you add and for ensuring that you have the right to use and submit it.',
        ts_s5_title: '5. Acceptable Use',
        ts_s5_intro: 'You agree not to:',
        ts_s5_list: '<li>use IntoDay for unlawful purposes</li><li>upload or submit harmful, abusive, infringing, or misleading content</li><li>interfere with the security or operation of the service</li><li>attempt to access data that does not belong to you</li><li>reverse engineer, copy, or misuse the service beyond normal permitted use</li>',
        ts_s5_footer: 'We may suspend or terminate access if we reasonably believe you have violated these Terms.',
        ts_s6_title: '6. Service Availability',
        ts_s6_desc: 'IntoDay is provided on an “as is” and “as available” basis. We may update, change, suspend, or discontinue parts of the service at any time, especially during the beta stage. We do not guarantee that IntoDay will always be available, error-free, or uninterrupted.',
        ts_s7_title: '7. Beta Status',
        ts_s7_desc: 'Because IntoDay is in an early stage, features may change frequently. You understand that some features may be incomplete, bugs or interruptions may occur, and product behavior may change over time. We appreciate feedback, but we are not obligated to implement any suggestions.',
        ts_s8_title: '8. Privacy',
        ts_s8_desc: 'Your use of IntoDay is also governed by our Privacy Policy. Please review the Privacy Policy to understand how we collect, use, and handle your information.',
        ts_s9_title: '9. Termination',
        ts_s9_desc: 'You may stop using IntoDay at any time. We may suspend or terminate your access to IntoDay at any time if you violate these Terms, if we need to protect the service, users, or our systems, or if we decide to discontinue the beta or service.',
        ts_s10_title: '10. Disclaimers',
        ts_s10_desc: 'IntoDay is a productivity tool only. It does not provide legal, medical, financial, or professional advice. We are not responsible for missed tasks, lost data, scheduling outcomes, or decisions made based on the use of IntoDay.',
        ts_s11_title: '11. Limitation of Liability',
        ts_s11_desc: 'To the maximum extent permitted by law, IntoDay and its operators will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of data, profits, or business opportunities resulting from your use of or inability to use the service.',
        ts_s12_title: '12. Changes to These Terms',
        ts_s12_desc: 'We may update these Terms from time to time. If we make material changes, we will update the Effective Date above. Your continued use of IntoDay after the updated Terms take effect means you agree to the revised Terms.',
        ts_s13_title: '13. Contact',
        ts_s13_desc: 'If you have questions about these Terms, you can contact us at: contact.intoday@gmail.com',
        help_hero_label: 'Support & Resources',
        help_hero_title: 'Help & Feedback',
        help_hero_desc: 'Questions, bugs, or ideas — we\'d love to hear from you. We build IntoDay based on how you plan your life.',
        help_card1_title: 'Share feedback',
        help_card1_desc: 'Tell us what feels useful, confusing, or missing. Your insights shape the future of the app.',
        help_card1_cta: 'Send feedback',
        help_card2_title: 'Report a bug',
        help_card2_desc: 'Something not working as expected? Let us know so we can fix it and smooth out your experience.',
        help_card2_cta: 'Report a bug',
        help_card3_title: 'Ask for help',
        help_card3_desc: 'Need help using IntoDay or understanding how a specific feature works? We\'re here for you.',
        help_card3_cta: 'Get help',
        faq_title: 'Frequently asked',
        faq_q1: 'What is IntoDay?',
        faq_a1: 'IntoDay is a lightweight day planner for the things you need to do today — without needing to assign exact times.',
        faq_q2: 'How is this different from a calendar?',
        faq_a2: 'Calendars are for exact events. IntoDay is for the things you want to place into your day without turning them into calendar entries.',
        faq_q3: 'Do I need to set exact times?',
        faq_a3: 'No. IntoDay is built around time periods like morning, afternoon, and evening — so you can stay organized without planning everything to the minute.',
        faq_q4: 'Can I move things later?',
        faq_a4: 'Yes. If plans change, you can move items to a later time period or another day without starting over.',
        faq_q5: 'Is this a to-do list app?',
        faq_a5: 'Not exactly. IntoDay gives your to-dos a place in the day, so they feel more organized than a simple list.',
        faq_q6: 'Who is IntoDay for?',
        faq_a6: 'It’s for anyone managing follow-ups, reminders, errands, and small plans that don’t need exact times.',
        help_contact_label: 'Still need assistance?',
        modal_optional: 'Optional',
        modal_form_error: 'Something went wrong.',
        modal_done: 'Done',
        modal_feedback_label: 'Share feedback',
        modal_feedback_title: 'What\'s on your mind?',
        modal_feedback_sub: 'Your thoughts help us shape IntoDay\'s future.',
        modal_feedback_q1: 'What would you like to share?',
        modal_feedback_p1: 'Tell us what feels useful, confusing, or missing…',
        modal_feedback_e1: 'Please share something with us.',
        modal_feedback_q2: 'What were you trying to do?',
        modal_feedback_p2: 'e.g. Setting up my morning routine',
        modal_feedback_q3: 'Your email',
        modal_feedback_p3: 'so we can follow up',
        modal_feedback_e3: 'Please enter a valid email.',
        modal_feedback_q4: 'Screenshot',
        modal_feedback_p4: 'Attach a screenshot',
        modal_feedback_btn: 'Send feedback',
        modal_feedback_s_title: 'Thanks — this helps us improve IntoDay.',
        modal_feedback_s_desc: 'We read every message. If you left your email, we\'ll follow up soon.',
        modal_bug_label: 'Report a bug',
        modal_bug_title: 'What went wrong?',
        modal_bug_sub: 'The more detail you share, the faster we can fix it.',
        modal_bug_q1: 'What happened?',
        modal_bug_p1: 'Describe the issue…',
        modal_bug_e1: 'Please describe what happened.',
        modal_bug_q2: 'What did you expect?',
        modal_bug_p2: 'What should have happened…',
        modal_bug_e2: 'Please describe what you expected.',
        modal_bug_q3: 'Device / browser',
        modal_bug_p3: 'e.g. iPhone, Chrome',
        modal_bug_q4: 'Your email',
        modal_bug_p4: 'so we can update you',
        modal_bug_q5: 'Screenshot',
        modal_bug_p5: 'Attach a screenshot',
        modal_bug_btn: 'Report a bug',
        modal_bug_s_title: 'Got it — we\'ll take a look.',
        modal_bug_s_desc: 'Thanks for taking the time to report this. It genuinely helps us improve IntoDay.',
        modal_help_label: 'Ask for help',
        modal_help_title: 'How can we help?',
        modal_help_sub: 'We reply personally to every request. Talk soon.',
        modal_help_q1: 'What do you need help with?',
        modal_help_p1: 'Describe your question…',
        modal_help_e1: 'Please tell us what you need help with.',
        modal_help_q2: 'Your email',
        modal_help_p2: 'your@email.com',
        modal_help_e2: 'Please enter a valid email.',
        modal_help_q3: 'Screenshot',
        modal_help_p3: 'Attach a screenshot',
        modal_help_btn: 'Get help',
        modal_help_s_title: 'Thanks for reaching out.',
        modal_help_s_desc: 'We\'ll reply to your email as soon as we can — usually within a day or two.',
    },
    zh: {
        flag: '🇨🇳',
        label: '中文',
        nav_cta: '免费开始',
        hero_title: '把事情和链接<br>留在今天',
        hero_sub: '用时段式的今日清单，把任务、链接、地点和资料留在同一个地方，承接你的每一天。',
        hero_cta: '免费开始',
        f1_label: '按时间段安排',
        f1_title: '不必塞进日历 也不用再怕忘记',
        f1_desc: '任何小事 都能轻松放进合适的时间段里',
        f2_label: '一键直达',
        f2_title: '每条事项 都能通往下一步',
        f2_desc: '链接 地点 文件和文字都能轻松输入 自动整理成可读内容 随时直接打开。',
        f3_label: '保持简单',
        f3_title: '今天的事 都留在同一页里',
        f3_desc: '你的一天集中在一处 清晰可见。要处理的内容，都能一直留在眼前',
        uc1_title: '工作上的后续事项',
        uc1_desc: '将交接 跟进和会后要处理的小事留在一处 不再散落在笔记 聊天和待办里',
        uc2_title: '课后和作业之间的小事',
        uc2_desc: '要交的东西 要看的资料 要回的消息 晚点要完成的任务等等 不用设定时间 只需放入合适的时段',
        uc3_title: '会不断变化的一天',
        uc3_desc: '买菜 去商店 旅行 城市散步 或忙碌又多变的一天里 事情都能随时移动 安排也依然清楚',
        quote: '不再被分散的任务、链接和精确的时间设定来回拉扯',
        quote_author: 'The IntoDay Philosophy',
        cta_title: '从今天开始 让事情有位置，让行动有入口！',
        cta_btn: '免费开始',
        footer_help: '帮助与反馈',
        footer_privacy: '隐私政策',
        footer_terms: '服务条款',
        footer_copy: '© 2026 IntoDay. 版权所有。',
        pp_title: 'IntoDay 隐私政策',
        pp_effective: '生效日期：2026/3/12',
        pp_intro: 'IntoDay（“我们”、“我们的”）尊重您的隐私。本隐私政策解释了我们在您使用 IntoDay 时收集哪些信息、我们如何使用这些信息以及您有哪些选择。',
        pp_desc: 'IntoDay 是一款将任务、提醒、跟进和微计划组织到全天时间块中的工具。',
        pp_contact_intro: '如果您对本隐私政策有任何疑问，可以通过以下方式联系我们：contact.intoday@gmail.com',
        pp_s1_title: '1. 我们是谁',
        pp_s1_desc: 'IntoDay 是 IntoDay 应用程序及相关网站的提供商。如果您对隐私或数据处理有任何疑问，可以通过以下方式联系我们：contact.intoday@gmail.com',
        pp_s2_title: '2. 我们收集的信息',
        pp_s2_desc: '我们仅收集提供及改进 IntoDay 所必需的信息。',
        pp_s2_1_title: '2.1 账户信息',
        pp_s2_1_desc: '如果您使用 Google 登录，我们可能会收到基本账户信息，例如：',
        pp_s2_1_list: '<li>您的电子邮件地址</li><li>您的 Google 账户标识符</li><li>您的姓名或个人资料图片（如果在登录权限中提供）</li>',
        pp_s2_1_meta: '我们使用这些信息来创建和管理您的账户，并让您安全登录。',
        pp_s2_2_title: '2.2 您添加到 IntoDay 的内容',
        pp_s2_2_desc: '当您使用 IntoDay 时，我们可能会存储您选择添加的内容，例如任务、提醒、笔记、链接、位置、文件相关引用以及您在应用中输入的其他任务相关文本。',
        pp_s2_2_meta: '我们使用这些信息来提供 IntoDay 的核心功能，包括显示、组织和同步您的内容。',
        pp_s2_3_title: '2.3 技术和使用数据',
        pp_s2_3_desc: '当您使用 IntoDay 时，我们可能会自动收集某些技术信息，例如：',
        pp_s2_3_list: '<li>设备和浏览器信息</li><li>IP 地址</li><li>日志数据</li><li>使用情况分析和产品交互数据</li>',
        pp_s2_3_meta: '我们使用这些信息来保持服务的安全运行、了解应用性能、修复漏洞并改进产品体验。',
        pp_s3_title: '3. 我们如何使用您的信息',
        pp_s3_desc: '我们使用您的信息来提供和维护 IntoDay、启用安全登录、存储和显示您的任务和内容、支持同步和账户相关功能、监控稳定性、性能和安全性，并随着时间的推移改进应用。',
        pp_s4_title: '4. 我们使用的第三方服务',
        pp_s4_desc: '我们使用值得信赖的第三方服务提供商来运营 IntoDay。',
        pp_s4_1_title: '4.1 Supabase',
        pp_s4_1_desc: '我们使用 Supabase 提供身份验证、数据库和后端相关服务。Supabase 可能会根据提供服务的需要存储您的账户数据和您添加到 IntoDay 的内容。',
        pp_s4_2_title: '4.2 Google 登录',
        pp_s4_2_desc: '如果您选择使用 Google 登录，Google 将提供身份验证过程，并可能根据您授予的权限与我们共享基本账户信息。',
        pp_s4_3_title: '4.3 Vercel',
        pp_s4_3_desc: '我们使用 Vercel 来托管和分发 IntoDay 网站和 Web 应用。Vercel 可能会处理技术信息（如 IP 地址、浏览器/设备详细信息和请求日志），用于托管、分发和安全目的。',
        pp_s5_title: '5. 我们如何分享信息',
        pp_s5_desc: '我们不会出售您的个人信息。我们仅在以下情况下共享您的信息：与帮助我们运营 IntoDay 的服务提供商共享；法律要求时；或为了保护 IntoDay 及其用户的安全、权利或完整性所必需时。',
        pp_s6_title: '6. 数据保留',
        pp_s6_desc: '我们保留您的信息的时间仅限于提供 IntoDay 和运营服务所需的时间。如果您注销账户或请求删除，我们将尽合理努力在合理期限内删除您的个人数据，除非法律、安全或运营原因要求我们保留某些信息。',
        pp_s7_title: '7. 数据安全',
        pp_s7_desc: '我们采取合理的各类技术和组织措施，保护您的信息免受未经授权的访问、丢失、误用或泄露。然而，没有任何系统是绝对安全的，我们无法保证绝对的安全。',
        pp_s8_title: '8. 您的选择和权利',
        pp_s8_desc: '根据您所在的地区，您可能拥有与个人数据相关的权利，包括访问、更正或请求删除数据的权利。如需提出请求，请联系：contact.intoday@gmail.com',
        pp_s9_title: '9. 儿童隐私',
        pp_s9_desc: 'IntoDay 不适用于未满适用法律要求的年龄且未经父母同意使用此类服务的儿童。我们不会在违反适用法律的情况下故意收集儿童的个人信息。',
        pp_s10_title: '10. 本隐私政策的变更',
        pp_s10_desc: '我们可能会不时更新本隐私政策。如果我们做出重大变更，我们将更新页面顶部的“生效日期”，并在适当时提供额外通知。',
        pp_s11_title: '11. 联系方式',
        pp_s11_desc: '如果您有任何问题、反馈或与隐私相关的请求，可以通过以下方式联系我们：contact.intoday@gmail.com',
        ts_title: 'IntoDay 服务条款',
        ts_effective: '生效日期：2026/3/12',
        ts_intro: '本服务条款（“条款”）约束您对比 IntoDay（“IntoDay”、“我们”、“我们的”）的访问和使用。',
        ts_agree: '访问或使用 IntoDay 即表示您同意这些条款。如果您不同意，请勿使用 IntoDay。',
        ts_s1_title: '1. 关于 IntoDay',
        ts_s1_desc: 'IntoDay 是一款将任务、提醒、跟进和微计划组织到全天时间块中的工具。IntoDay 目前作为早期阶段产品 / Beta 服务提供。某些功能可能会随时间变化、更新或移除。',
        ts_s2_title: '2. 适用性',
        ts_s2_desc: '只有当您可以在适用于您的法律下合法签署具有约束力的协议时，您才可以使用 IntoDay。',
        ts_s3_title: '3. 您的账户',
        ts_s3_intro: '您可以使用 Google 身份验证登录 IntoDay。您负责：',
        ts_s3_list: '<li>维护您的账户安全</li><li>妥善保管您的登录凭证</li><li>账户下发生的所有活动</li>',
        ts_s3_contact: '如果您认为您的账户在未经授权的情况下被访问，请联系我们：contact.intoday@gmail.com',
        ts_s4_title: '4. 您的内容',
        ts_s4_desc: '您可以向 IntoDay 添加内容，包括任务、提醒、笔记、链接、位置、文件相关引用和其他文本。您保留对提交给 IntoDay 的内容的所有权。您授予我们有限的权利，仅在操作和提供服务所必需的情况下存储、处理和显示您的内容。您对所添加的内容负责，并确保您有权使用和提交该内容。',
        ts_s5_title: '5. 可接受的使用方式',
        ts_s5_intro: '您同意不：',
        ts_s5_list: '<li>将 IntoDay 用于非法目的</li><li>上传或提交有害、辱骂性、侵权或误导性的内容</li><li>干扰服务的安全或运营</li><li>试图访问不属于您的数据</li><li>进行逆向工程、复制或在正常允许范围之外滥用服务</li>',
        ts_s5_footer: '如果我们合理认为您违反了这些条款，我们可能会暂停或终止您的访问权限。',
        ts_s6_title: '6. 服务可用性',
        ts_s6_desc: 'IntoDay 按“现状”和“可用性”基础提供。我们可能会随时更新、更改、暂停或中断部分服务，特别是在 Beta 阶段。我们不保证 IntoDay 始终可用、无错误或不中断。',
        ts_s7_title: '7. Beta 状态',
        ts_s7_desc: '由于 IntoDay 处于早期阶段，功能可能会频繁更改。您理解某些功能可能不完整，可能会出现错误或中断，且产品行为可能会随时间变化。我们感谢反馈，但没有义务实施任何建议。',
        ts_s8_title: '8. 隐私',
        ts_s8_desc: '您对 IntoDay 的使用也受我们的隐私政策约束。请查看隐私政策以了解我们如何收集、使用和处理您的信息。',
        ts_s9_title: '9. 终止',
        ts_s9_desc: '您可以随时停止使用 IntoDay。如果我们认为您违反了这些条款、我们需要保护服务、用户或我们的系统，或我们决定终止 Beta 或服务，我们可能会随时暂停或终止您对 IntoDay 的访问权限。',
        ts_s10_title: '10. 免责声明',
        ts_s10_desc: 'IntoDay 仅作为生产力工具。它不提供法律、医学、财务或专业建议。对于错过的任务、丢失的数据、调度结果或基于使用 IntoDay 做出的决定，我们概不负责。',
        ts_s11_title: '11. 责任限制',
        ts_s11_desc: '在法律允许的最大范围内，IntoDay 及其运营商不对因使用或无法使用服务而导致的任何间接、附带、特别、后果性或惩罚性损害赔偿，或任何数据、利润或业务机会的损失负责。',
        ts_s12_title: '12. 本条款的变更',
        ts_s12_desc: '我们可能会不时更新这些条款。如果我们做出重大变更，我们将更新上方的有效日期。在更新后的条款生效后继续使用 IntoDay 即表示您同意修订后的条款。',
        ts_s13_title: '13. 联系方式',
        ts_s13_desc: '如果您对这些条款有疑问，可以通过以下方式联系：contact.intoday@gmail.com',
        help_hero_label: '支持与资源',
        help_hero_title: '帮助与反馈',
        help_hero_desc: '无论是疑问、漏洞还是创意，我们都期待您的声音。我们根据您的生活规划方式来构建 IntoDay。',
        help_card1_title: '分享反馈',
        help_card1_desc: '告诉我们哪些功能有用、哪些令人困惑或缺失。您的见解将决定应用的未来。',
        help_card1_cta: '发送反馈',
        help_card2_title: '报告漏洞',
        help_card2_desc: '有些功能不如预期？请告诉我们，以便我们修复并优化您的体验。',
        help_card2_cta: '报告漏洞',
        help_card3_title: '寻求帮助',
        help_card3_desc: '在使用 IntoDay 或理解特定功能时需要帮助吗？我们随时为您服务。',
        help_card3_cta: '获取帮助',
        faq_title: '常见问题',
        faq_q1: '什么是 IntoDay？',
        faq_a1: 'IntoDay 是一款轻量级的日程规划应用，专门为您今天需要做的事情而设计 —— 无需分配精确的时间。',
        faq_q2: '这与日历有何不同？',
        faq_a2: '日历用于确定的事件。IntoDay 则用于您想放入一天中但又不想将其变成日历项的事情。',
        faq_q3: '我需要设定精确的时间吗？',
        faq_a3: '不需要。IntoDay 围绕早晨、下午和晚上等时段构建 —— 因此您可以保持条理，而无需精确到分钟地规划一切。',
        faq_q4: '我可以稍后再处理吗？',
        faq_a4: '是的。如果计划有变，您可以将项目移动到稍后的时段或另一天，而无需重新开始。',
        faq_q5: '这是一个待办事项应用吗？',
        faq_a5: '不完全是。IntoDay 为您的待办事项在一天中提供了一个位置，使它们感觉比简单的清单更有条理。',
        faq_q6: 'IntoDay 适合谁？',
        faq_a6: '它适合任何管理跟进事项、提醒、杂事以及不需要精确时间的简单计划的人。',
        help_contact_label: '还需要其他帮助吗?',
        modal_optional: '可选',
        modal_form_error: '出错了，请稍后再试。',
        modal_done: '完成',
        modal_feedback_label: '分享反馈',
        modal_feedback_title: '您有什么想法？',
        modal_feedback_sub: '您的想法能帮助我们更好地塑造 IntoDay 的未来。',
        modal_feedback_q1: '您想分享什么？',
        modal_feedback_p1: '告诉我们哪些功能有用、令人困惑或缺失……',
        modal_feedback_e1: '请分享您的想法。',
        modal_feedback_q2: '您当时正尝试做什么？',
        modal_feedback_p2: '例如：设置我的早晨例行任务',
        modal_feedback_q3: '您的邮箱',
        modal_feedback_p3: '以便我们后续联系您',
        modal_feedback_e3: '请输入有效的邮箱地址。',
        modal_feedback_q4: '屏幕截图',
        modal_feedback_p4: '添加屏幕截图',
        modal_feedback_btn: '发送反馈',
        modal_feedback_s_title: '感谢反馈 — 这有助于我们改进 IntoDay。',
        modal_feedback_s_desc: '我们会阅读每一条消息。如果您留下了邮箱，我们会尽快回复。',
        modal_bug_label: '报告漏洞',
        modal_bug_title: '出了什么问题？',
        modal_bug_sub: '您分享的细节越多，我们修复的速度就越快。',
        modal_bug_q1: '发生了什么？',
        modal_bug_p1: '详细描述该问题……',
        modal_bug_e1: '请描述发生的问题。',
        modal_bug_q2: '您的预期是什么？',
        modal_bug_p2: '原本应该发生什么……',
        modal_bug_e2: '请描述您的预期结果。',
        modal_bug_q3: '设备 / 浏览器',
        modal_bug_p3: '例如：iPhone, Chrome',
        modal_bug_q4: '您的邮箱',
        modal_bug_p4: '以便我们向您同步进度',
        modal_bug_q5: '屏幕截图',
        modal_bug_p5: '添加屏幕截图',
        modal_bug_btn: '报告漏洞',
        modal_bug_s_title: '收到 — 我们会查看的。',
        modal_bug_s_desc: '感谢您花时间报告。这确实能帮助我们改进 IntoDay。',
        modal_help_label: '获取帮助',
        modal_help_title: '我们能提供什么帮助？',
        modal_help_sub: '我们会亲自回复每一个请求。稍后见。',
        modal_help_q1: '您需要什么帮助？',
        modal_help_p1: '描述您的问题……',
        modal_help_e1: '请告诉我们您需要什么帮助。',
        modal_help_q2: '您的邮箱',
        modal_help_p2: 'your@email.com',
        modal_help_e2: '请输入有效的邮箱地址。',
        modal_help_q3: '屏幕截图',
        modal_help_p3: '添加屏幕截图',
        modal_help_btn: '获取帮助',
        modal_help_s_title: '感谢联系我们。',
        modal_help_s_desc: '我们会尽快回复您的邮件 — 通常在一到两天内。',
    },
    ms: {
        flag: '🇲🇾',
        label: 'MY',
        nav_cta: 'Mulakan percuma',
        hero_title: 'Simpan setiap perkara dan akses masuk<br>dalam hari ini',
        hero_sub: 'Gunakan pendekatan blok masa untuk mengurus hari anda. Simpan tugasan, pautan, lokasi, dan dokumen di satu tempat, mengurangkan beban untuk mencari semula konteks asal.',
        hero_cta: 'Mulakan percuma',
        f1_label: 'Susun mengikut slot masa',
        f1_title: 'Tak perlu sesakkan kalendar, tak perlu lagi takut lupa',
        f1_desc: 'Apa sahaja perkara kecil boleh diletakkan dalam slot masa yang sesuai dengan mudah',
        f2_label: 'Akses terus',
        f2_title: 'Setiap item membawa anda ke langkah seterusnya',
        f2_desc: 'Pautan, lokasi, fail dan teks – semuanya mudah dimasukkan dan disusun menjadi kandungan yang senang dibaca, sedia dibuka bila-bila masa.',
        f3_label: 'Kekalkan kesederhanaan',
        f3_title: 'Hal hari ini, semuanya di satu halaman sahaja',
        f3_desc: 'Hari anda terfokus di satu tempat, jelas kelihatan. Segala yang perlu dilakukan sentiasa berada di depan mata.',
        uc1_title: 'Tindakan susulan kerja',
        uc1_desc: 'Simpan serahan, tindakan susulan dan tugasan selepas mesyuarat di satu tempat – tidak lagi bersepah dalam nota, sembang atau senarai tugasan.',
        uc2_title: 'Antara waktu sekolah dan kerja sekolah',
        uc2_desc: 'Barang untuk dihantar, bahan bacaan, mesej untuk dibalas, tugasan kemudian hari... tidak perlu tetapkan masa tepat, cukup sekadar masukkan ke dalam slot yang sesuai.',
        uc3_title: 'Untuk hari yang sentiasa berubah',
        uc3_desc: 'Membeli-belah, melancong, bersiar-siar di bandar, atau hari yang sibuk dan berubah-ubah – segalanya mudah dialihkan dan rancangan tetap jelas.',
        quote: '“Tidak lagi ditarik ke sana sini oleh tugasan yang bertaburan, pautan, dan penetapan masa yang kaku”',
        quote_attr: 'The IntoDay Philosophy',
        cta_title: 'Mula hari ini, beri setiap perkara tempatnya, beri setiap tindakan aksesnya！',
        cta_btn: 'Mulakan percuma',
        footer_help: 'Bantuan / Maklum Balas',
        footer_privacy: 'Dasar Privasi',
        footer_terms: 'Syarat Perkhidmatan',
        footer_copy: '© 2026 IntoDay. Hak cipta terpelihara.',
        pp_title: 'Dasar Privasi IntoDay',
        pp_effective: 'Tarikh Berkuat Kuasa: @2026/3/12',
        pp_intro: 'IntoDay ("kami", "kita" atau "milik kami") menghormati privasi anda. Dasar Privasi ini menerangkan maklumat yang kami kumpul, cara kami menggunakannya, dan pilihan yang anda ada semasa menggunakan IntoDay.',
        pp_desc: 'IntoDay ialah alat untuk mengatur tugasan, peringatan, tindakan susulan dan rancangan kecil ke dalam blok masa sepanjang hari.',
        pp_contact_intro: 'Jika anda mempunyai sebarang soalan tentang Dasar Privasi ini, anda boleh menghubungi kami di: contact.intoday@gmail.com',
        pp_s1_title: '1. Siapa Kami',
        pp_s1_desc: 'IntoDay ialah penyedia aplikasi IntoDay dan laman web berkaitan. Jika anda mempunyai soalan tentang privasi atau pengendalian data, anda boleh menghubungi kami di: contact.intoday@gmail.com',
        pp_s2_title: '2. Maklumat yang Kami Kumpul',
        pp_s2_desc: 'Kami hanya mengumpul maklumat yang diperlukan untuk menyediakan dan menambah baik IntoDay.',
        pp_s2_1_title: '2.1 Maklumat Akaun',
        pp_s2_1_desc: 'Jika anda log masuk dengan Google, kami mungkin menerima maklumat akaun asas seperti:',
        pp_s2_1_list: '<li>alamat e-mel anda</li><li>pengecam akaun Google anda</li><li>nama atau imej profil anda, jika disediakan melalui kebenaran log masuk anda</li>',
        pp_s2_1_meta: 'Kami menggunakan maklumat ini untuk membina dan mengurus akaun anda dan membolehkan anda log masuk dengan selamat.',
        pp_s2_2_title: '2.2 Kandungan yang Anda Tambah ke IntoDay',
        pp_s2_2_desc: 'Apabila anda menggunakan IntoDay, kami mungkin menyimpan kandungan yang anda pilih untuk tambah, seperti tugasan, peringatan, nota, pautan, lokasi, rujukan berkaitan fail, dan teks berkaitan tugasan lain yang anda masukkan ke dalam aplikasi.',
        pp_s2_2_meta: 'Kami menggunakan maklumat ini untuk menyediakan fungsi teras IntoDay, termasuk paparan, organisasi, dan penyelarasan kandungan anda.',
        pp_s2_3_title: '2.3 Data Teknikal dan Penggunaan',
        pp_s2_3_desc: 'Apabila anda menggunakan IntoDay, kami mungkin mengumpul maklumat teknikal tertentu secara automatik, seperti:',
        pp_s2_3_list: '<li>maklumat peranti dan pelayar</li><li>alamat IP</li><li>data log</li><li>analitik penggunaan dan data interaksi produk</li>',
        pp_s2_3_meta: 'Kami menggunakan maklumat ini untuk memastikan perkhidmatan berjalan dengan selamat, memahami prestasi aplikasi, membetulkan pepijat, dan menambah baik pengalaman produk.',
        pp_s3_title: '3. Cara Kami Menggunakan Maklumat Anda',
        pp_s3_desc: 'Kami menggunakan maklumat anda untuk menyediakan dan mengekalkan IntoDay, membolehkan log masuk selamat, menyimpan dan memaparkan tugasan dan kandungan anda, menyokong fungsi penyelarasan dan berkaitan akaun, memantau kestabilan, prestasi, dan keselamatan, serta menambah baik aplikasi dari semasa ke semasa.',
        pp_s4_title: '4. Perkhidmatan Pihak Ketiga yang Kami Gunakan',
        pp_s4_desc: 'Kami menggunakan penyedia perkhidmatan pihak ketiga yang dipercayai untuk mengendalikan IntoDay.',
        pp_s4_1_title: '4.1 Supabase',
        pp_s4_1_desc: 'Kami menggunakan Supabase untuk pengesahan, pangkalan data, dan perkhidmatan berkaitan backend. Supabase mungkin menyimpan data akaun anda dan kandungan yang anda tambah ke IntoDay seperti yang diperlukan untuk menyediakan perkhidmatan.',
        pp_s4_2_title: '4.2 Log Masuk Google',
        pp_s4_2_desc: 'Jika anda memilih untuk log masuk dengan Google, Google menyediakan proses pengesahan dan mungkin berkongsi maklumat akaun asas dengan kami, bergantung pada kebenaran yang anda berikan.',
        pp_s4_3_title: '4.3 Vercel',
        pp_s4_3_desc: 'Kami menggunakan Vercel untuk mengehos dan menyampaikan laman web serta laman web aplikasi IntoDay. Vercel mungkin memproses maklumat teknikal seperti alamat IP, butiran pelayar/peranti, dan log permintaan untuk tujuan pengehosan, penyampaian, dan keselamatan.',
        pp_s5_title: '5. Cara Kami Berkongsi Maklumat',
        pp_s5_desc: 'Kami tidak menjual maklumat peribadi anda. Kami mungkin berkongsi maklumat anda hanya dengan penyedia perkhidmatan yang membantu kami mengendalikan IntoDay, apabila dikehendaki oleh undang-undang, atau apabila perlu untuk melindungi keselamatan, hak, atau integriti IntoDay dan penggunanya.',
        pp_s6_title: '6. Pengekalan Data',
        pp_s6_desc: 'Kami menyimpan maklumat anda hanya selama yang diperlukan untuk menyediakan IntoDay dan mengendalikan perkhidmatan. Jika anda memadamkan akaun anda atau meminta pemadaman, kami akan melakukan usaha yang munasabah untuk memadamkan data peribadi anda dalam tempoh yang munasabah, melainkan kami dikehendaki menyimpan maklumat tertentu untuk sebab undang-undang, keselamatan, atau operasi.',
        pp_s7_title: '7. Keselamatan Data',
        pp_s7_desc: 'Kami mengambil langkah-langkah teknikal dan organisasi yang munasabah untuk melindungi maklumat anda daripada akses yang tidak dibenarkan, kehilangan, penyalahgunaan, atau pendedahan. Walau bagaimanapun, tiada sistem yang selamat sepenuhnya, dan kami tidak dapat menjamin keselamatan mutlak.',
        pp_s8_title: '8. Pilihan dan Hak Anda',
        pp_s8_desc: 'Bergantung pada lokasi anda, anda mungkin mempunyai hak mengenai data peribadi anda, termasuk hak untuk mengakses, membetulkan, atau meminta pemadaman data anda. Untuk membuat permintaan, hubungi kami di: contact.intoday@gmail.com',
        pp_s9_title: '9. Privasi Kanak-kanak',
        pp_s9_desc: 'IntoDay tidak ditujukan untuk kanak-kanak di bawah umur yang dikehendaki oleh undang-undang yang terpakai untuk menggunakan perkhidmatan tersebut tanpa persetujuan ibu bapa. Kami tidak sengaja mengumpul maklumat peribadi daripada kanak-kanak yang melanggar undang-undang yang terpakai.',
        pp_s10_title: '10. Perubahan kepada Dasar Privasi Ini',
        pp_s10_desc: 'Kami mungkin mengemas kini Dasar Privasi ini dari semasa ke semasa. Jika kami membuat perubahan material, kami akan mengemas kini "Tarikh Berkuat Kuasa" di bahagian atas halaman ini dan, jika sesuai, memberikan notis tambahan.',
        pp_s11_title: '11. Hubungi',
        pp_s11_desc: 'Jika anda mempunyai sebarang soalan, maklum balas, atau permintaan berkaitan privasi, anda boleh menghubungi kami di: contact.intoday@gmail.com',
        ts_title: 'Syarat Perkhidmatan IntoDay',
        ts_effective: 'Tarikh Berkuat Kuasa: @2026/3/12',
        ts_intro: 'Syarat Perkhidmatan ini ("Syarat") mengawal akses anda kepada dan penggunaan IntoDay ("IntoDay", "kami", "kita" atau "milik kami").',
        ts_agree: 'Dengan mengakses atau menggunakan IntoDay, anda bersetuju dengan Syarat ini. Jika anda tidak bersetuju, sila jangan gunakan IntoDay.',
        ts_s1_title: '1. Mengenai IntoDay',
        ts_s1_desc: 'IntoDay ialah alat untuk mengatur tugasan, peringatan, tindakan susulan dan rancangan kecil ke dalam blok masa sepanjang hari. IntoDay kini disediakan sebagai produk peringkat awal / perkhidmatan beta. Sesetengah ciri mungkin berubah, dikemas kini, atau dialih keluar dari semasa ke semasa.',
        ts_s2_title: '2. Kelayakan',
        ts_s2_desc: 'Anda boleh menggunakan IntoDay hanya jika anda boleh memeterai perjanjian yang mengikat secara sah di bawah undang-undang yang terpakai kepada anda.',
        ts_s3_title: '3. Akaun Anda',
        ts_s3_intro: 'Anda boleh log masuk ke IntoDay menggunakan pengesahan Google. Anda bertanggungjawab untuk:',
        ts_s3_list: '<li>mengekalkan keselamatan akaun anda</li><li>memastikan kelayakan log masuk anda selamat</li><li>semua aktiviti yang berlaku di bawah akaun anda</li>',
        ts_s3_contact: 'Jika anda percaya akaun anda telah diakses tanpa kebenaran, sila hubungi kami di: contact.intoday@gmail.com',
        ts_s4_title: '4. Kandungan Anda',
        ts_s4_desc: 'Anda boleh menambah kandungan ke IntoDay, termasuk tugasan, peringatan, nota, pautan, lokasi, rujukan berkaitan fail, dan teks lain. Anda mengekalkan pemilikan kandungan yang anda serahkan kepada IntoDay. Anda memberi kami hak terhad untuk menyimpan, memproses, dan memaparkan kandungan anda hanya seperti yang diperlukan untuk mengendalikan dan menyediakan perkhidmatan. Anda bertanggungjawab ke atas kandungan yang anda tambah dan untuk memastikan bahawa anda mempunyai hak untuk menggunakan dan menyerahkannya.',
        ts_s5_title: '5. Penggunaan yang Boleh Diterima',
        ts_s5_intro: 'Anda bersetuju untuk tidak:',
        ts_s5_list: '<li>menggunakan IntoDay untuk tujuan menyalahi undang-undang</li><li>muat naik atau menyerahkan kandungan yang berbahaya, menyakitkan hati, melanggar hak, atau mengelirukan</li><li>mengganggu keselamatan atau operasi perkhidmatan</li><li>percubaan untuk mengakses data yang bukan milik anda</li><li>melakukan kejuruteraan terbalik, menyalin, atau menyalahgunakan perkhidmatan melebihi penggunaan biasa yang dibenarkan</li>',
        ts_s5_footer: 'Kami mungkin memggantung atau menamatkan akses jika kami merasai secara munasabah anda telah melanggar Syarat ini.',
        ts_s6_title: '6. Ketersediaan Perkhidmatan',
        ts_s6_desc: 'IntoDay disediakan atas dasar "sebagaimana adanya" dan "sebagaimana tersedia". Kami mungkin mengemas kini, menukar, memggantung, atau membatalkan bahagian perkhidmatan pada bila-bila masa, terutamanya semasa peringkat beta. Kami tidak menjamin bahawa IntoDay akan sentiasa tersedia, bebas ralat, atau tidak terganggu.',
        ts_s7_title: '7. Status Beta',
        ts_s7_desc: 'Kerana IntoDay berada di peringkat awal, ciri mungkin kerap berubah. Anda memahami bahawa sesetengah ciri mungkin tidak lengkap, pepijat atau gangguan mungkin berlaku, dan tingkah laku produk mungkin berubah dari semasa ke semasa. Kami menghargai maklum balas, tetapi kami tidak berkewajipan untuk melaksanakan sebarang cadangan.',
        ts_s8_title: '8. Privasi',
        ts_s8_desc: 'Penggunaan IntoDay oleh anda juga dikawal oleh Dasar Privasi kami. Sila semak Dasar Privasi untuk memahami cara kami mengumpul, menggunakan dan mengendalikan maklumat anda.',
        ts_s9_title: '9. Penamatan',
        ts_s9_desc: 'Anda boleh berhenti menggunakan IntoDay pada bila-bila masa. Kami mungkin memggantung atau menamatkan akses anda kepada IntoDay pada bila-bila masa jika anda melanggar Syarat ini, jika kami perlu melindungi perkhidmatan, pengguna, atau sistem kami, atau jika kami memutuskan untuk membatalkan beta atau perkhidmatan.',
        ts_s10_title: '10. Penafian',
        ts_s10_desc: 'IntoDay ialah alat produktiviti sahaja. Ia tidak menyediakan nasihat undang-undang, perubatan, kewangan, atau profesional. Kami tidak bertanggungjawab ke atas tugasan yang terlepas, data yang hilang, keputusan penjadualan, atau keputusan yang dibuat berdasarkan penggunaan IntoDay.',
        ts_s11_title: '11. Had Liabiliti',
        ts_s11_desc: 'Setakat yang dibenarkan oleh undang-undang, IntoDay dan pengendalinya tidak akan bertanggungjawab ke atas sebarang kerosakan tidak langsung, sampingan, khas, berbangkit, atau punitif, atau untuk sebarang kehilangan data, keuntungan, atau peluang perniagaan yang terhasil daripada penggunaan atau ketidakupayaan anda untuk menggunakan perkhidmatan.',
        ts_s12_title: '12. Perubahan kepada Syarat Ini',
        ts_s12_desc: 'Kami mungkin mengemas kini Syarat ini dari semasa ke semasa. Jika kami membuat perubahan material, kami akan mengemas kini Tarikh Berkuat Kuasa di atas. Penggunaan berterusan IntoDay oleh anda selepas Syarat yang dikemas kini berkuat kuasa bermakna anda bersetuju dengan Syarat yang disemak semula.',
        ts_s13_title: '13. Hubungi',
        ts_s13_desc: 'Jika anda mempunyai soalan tentang Syarat ini, anda boleh menghubungi kami di: contact.intoday@gmail.com',
        help_hero_label: 'Sokongan & Sumber',
        help_hero_title: 'Bantuan & Maklum Balas',
        help_hero_desc: 'Soalan, pepijat, atau idea — kami ingin mendengar daripada anda. Kami membina IntoDay berdasarkan cara anda merancang kehidupan anda.',
        help_card1_title: 'Kongsi maklum balas',
        help_card1_desc: 'Beritahu kami apa yang terasa berguna, mengelirukan, atau hilang. Wawasan anda membentuk masa depan aplikasi.',
        help_card1_cta: 'Hantar maklum balas',
        help_card2_title: 'Laporkan pepijat',
        help_card2_desc: 'Sesuatu tidak berfungsi seperti yang dijangkakan? Beritahu kami supaya kami boleh memperbaikinya dan melancarkan pengalaman anda.',
        help_card2_cta: 'Lapor pepijat',
        help_card3_title: 'Tanya bantuan',
        help_card3_desc: 'Perlu bantuan menggunakan IntoDay atau memahami cara ciri tertentu berfungsi? Kami di sini untuk anda.',
        help_card3_cta: 'Dapatkan bantuan',
        faq_title: 'Soalan Lazim',
        faq_q1: 'Apakah IntoDay?',
        faq_a1: 'IntoDay ialah perancang hari yang ringan untuk perkara yang perlu anda lakukan hari ini — tanpa perlu menetapkan masa yang tepat.',
        faq_q2: 'Bagaimanakah ia berbeza daripada kalendar?',
        faq_a2: 'Kalendar adalah untuk acara yang tepat. IntoDay adalah untuk perkara yang anda ingin letakkan dalam hari anda tanpa menjadikannya entri kalendar.',
        faq_q3: 'Adakah saya perlu menetapkan masa yang tepat?',
        faq_a3: 'Tidak. IntoDay dibina di sekitar tempoh masa seperti pagi, petang, dan malam — supaya anda boleh kekal teratur tanpa merancang segala-galanya mengikut minit.',
        faq_q4: 'Bolehkah saya memindahkan perkara kemudian?',
        faq_a4: 'Ya. Jika rancangan berubah, anda boleh memindahkan item ke tempoh masa yang lebih lewat atau hari lain tanpa bermula semula.',
        faq_q5: 'Adakah ini aplikasi senarai tugasan?',
        faq_a5: 'Tidak juga. IntoDay memberi tugasan anda tempat dalam hari tersebut, jadi ia berasa lebih teratur daripada senarai biasa.',
        faq_q6: 'Siapakah IntoDay untuk?',
        faq_a6: 'Ia untuk sesiapa sahaja yang menguruskan tindakan susulan, peringatan, urusan, dan rancangan kecil yang tidak memerlukan masa yang tepat.',
        help_contact_label: 'Masih memerlukan bantuan?',
        modal_optional: 'Pilihan',
        modal_form_error: 'Sesuatu telah berlaku. Sila cuba sebentar lagi.',
        modal_done: 'Selesai',
        modal_feedback_label: 'Kongsi maklum balas',
        modal_feedback_title: 'Apa yang ada di fikiran anda?',
        modal_feedback_sub: 'Pemikiran anda membantu kami membentuk masa depan IntoDay.',
        modal_feedback_q1: 'Apa yang anda ingin kongsikan?',
        modal_feedback_p1: 'Beritahu kami apa yang terasa berguna, mengelirukan, atau hilang…',
        modal_feedback_e1: 'Sila kongsi sesuatu dengan kami.',
        modal_feedback_q2: 'Apa yang anda cuba lakukan?',
        modal_feedback_p2: 'cth. Menetapkan rutin pagi saya',
        modal_feedback_q3: 'E-mel anda',
        modal_feedback_p3: 'supaya kami boleh susul balik',
        modal_feedback_e3: 'Sila masukkan e-mel yang sah.',
        modal_feedback_q4: 'Tangkapan skrin',
        modal_feedback_p4: 'Lampirkan tangkapan skrin',
        modal_feedback_btn: 'Hantar maklum balas',
        modal_feedback_s_title: 'Terima kasih — ini membantu kami menambah baik IntoDay.',
        modal_feedback_s_desc: 'Kami membaca setiap mesej. Jika anda meninggalkan e-mel, kami akan susul balik tidak lama lagi.',
        modal_bug_label: 'Laporkan bug',
        modal_bug_title: 'Apa yang salah?',
        modal_bug_sub: 'Lebih banyak perincian yang anda kongsi, lebih pantas kami boleh membaikinya.',
        modal_bug_q1: 'Apa yang berlaku?',
        modal_bug_p1: 'Terangkan masalah…',
        modal_bug_e1: 'Sila terangkan apa yang berlaku.',
        modal_bug_q2: 'Apa yang anda jangkakan?',
        modal_bug_p2: 'Apa yang sepatutnya berlaku…',
        modal_bug_e2: 'Sila terangkan apa yang anda jangkakan.',
        modal_bug_q3: 'Peranti / pelayar',
        modal_bug_p3: 'cth. iPhone, Chrome',
        modal_bug_q4: 'E-mel anda',
        modal_bug_p4: 'supaya kami boleh mengemas kini anda',
        modal_bug_q5: 'Tangkapan skrin',
        modal_bug_p5: 'Lampirkan tangkapan skrin',
        modal_bug_btn: 'Laporkan bug',
        modal_bug_s_title: 'Faham — kami akan melihatnya.',
        modal_bug_s_desc: 'Terima kasih kerana meluangkan masa untuk melaporkan perkara ini. Ia benar-benar membantu kami menambah baik IntoDay.',
        modal_help_label: 'Minta bantuan',
        modal_help_title: 'Bagaimana kami boleh membantu?',
        modal_help_sub: 'Kami membalas secara peribadi kepada setiap permintaan. Jumpa lagi.',
        modal_help_q1: 'Apa yang anda perlukan bantuan?',
        modal_help_p1: 'Terangkan soalan anda…',
        modal_help_e1: 'Sila beritahu kami perkara yang anda perlukan bantuan.',
        modal_help_q2: 'E-mel anda',
        modal_help_p2: 'e-mel@anda.com',
        modal_help_e2: 'Sila masukkan e-mel yang sah.',
        modal_help_q3: 'Tangkapan skrin',
        modal_help_p3: 'Lampirkan tangkapan skrin',
        modal_help_btn: 'Dapatkan bantuan',
        modal_help_s_title: 'Terima kasih kerana menghubungi kami.',
        modal_help_s_desc: 'Kami akan membalas e-mel anda secepat mungkin — biasanya dalam satu atau dua hari.',
    },
    ja: {
        flag: '🇯🇵',
        label: '日本語',
        nav_cta: '無料で始める',
        hero_title: '今日の中に、やることと次の行動を',
        hero_sub: 'タスクもリンクも場所も資料も、今日の中でひとつに。時間を細かく決めなくても、次にやることへすぐ戻れます。',
        hero_cta: '無料で始める',
        f1_label: '時間帯で整理する',
        f1_title: 'カレンダーに入れなくていい。<br>忘れる心配もいらない。',
        f1_desc: '小さなことでも、合う時間帯にさっと置けます。',
        f2_label: 'すぐに開ける',
        f2_title: 'すべての項目が、次の一歩につながる',
        f2_desc: 'リンク、場所、ファイル、テキストも簡単に追加でき、読みやすく整理されて、必要なときにすぐ開けます。',
        f3_label: 'シンプルに保つ',
        f3_title: '今日のことは、<br>一ページにまとめておける',
        f3_desc: '一日の流れがひとまとめになり、見通しが良くなります。やるべきことが、常に目の届く場所にあります。',
        uc1_title: '仕事のフォローアップ',
        uc1_desc: '引き継ぎやフォローアップ、会議後のタスクを一箇所に。メモやチャット、ToDoリストに散らばりません。',
        uc2_title: '授業や課題の合間に',
        uc2_desc: '提出するもの、読む資料、返信、あとでやること。正確な時間を決めなくても、合う時間帯に入れるだけ。',
        uc3_title: '変わり続ける一日に',
        uc3_desc: '買い物や旅行、街歩き、予定が変わりやすい日でも、流れに合わせて動かせて、見通しも保てます。',
        quote: '散らばることにも、詰め込みすぎることにも、もう振り回されない。',
        quote_author: 'The IntoDay Philosophy',
        cta_title: '今日から、やることに場所を、行動に入り口を！',
        cta_btn: '無料で始める',
        footer_help: 'ヘルプ / フィードバック',
        footer_privacy: 'プライバシーポリシー',
        footer_terms: '利用規約',
        footer_copy: '© 2026 IntoDay. 全著作権所有。',
        pp_title: 'IntoDay プライバシーポリシー',
        pp_effective: '発効日：@2026/3/12',
        pp_intro: 'IntoDay（「私たち」、「私たちの」）はお客様のプライバシーを尊重します。このプライバシーポリシーでは、IntoDayの使用時に収集する情報、その使用方法、およびお客様の選択肢について説明します。',
        pp_desc: 'IntoDayは、タスク、リマインダー、フォローアップ、および小さな予定を一日の時間ブロックに整理するためのツールです。',
        pp_contact_intro: 'このプライバシーポリシーに関するご質問がある場合は、以下までお問い合わせください: contact.intoday@gmail.com',
        pp_s1_title: '1. 私たちについて',
        pp_s1_desc: 'IntoDayは、IntoDayアプリおよび関連ウェブサイトの提供者です。プライバシーやデータの取り扱いに関するご質問は、以下までお問い合わせください: contact.intoday@gmail.com',
        pp_s2_title: '2. 収集する情報',
        pp_s2_desc: '私たちは、IntoDayの提供および改善に必要な情報のみを収集します。',
        pp_s2_1_title: '2.1 アカウント情報',
        pp_s2_1_desc: 'Googleでサインインした場合、以下のような基本アカウント情報を受け取ることがあります：',
        pp_s2_1_list: '<li>メールアドレス</li><li>Googleアカウント識別子</li><li>ログイン権限を通じて提供された場合、名前またはプロフィール画像</li>',
        pp_s2_1_meta: 'これらの情報は、アカウントの作成と管理、および安全なログインのために使用されます。',
        pp_s2_2_title: '2.2 IntoDayに追加されるコンテンツ',
        pp_s2_2_desc: 'IntoDayを使用する際、タスク、リマインダー、メモ、リンク、場所、ファイル関連の参照、およびアプリに入力したその他のタスク関連テキストなど、お客様が追加することを選択したコンテンツを保存することがあります。',
        pp_s2_2_meta: 'これらの情報は、コンテンツの表示、整理、同期など、IntoDayのコア機能を提供するために使用されます。',
        pp_s2_3_title: '2.3 技術および利用データ',
        pp_s2_3_desc: 'IntoDayを使用する際、以下のような特定の技術情報を自動的に収集することがあります：',
        pp_s2_3_list: '<li>デバイスおよびブラウザ情報</li><li>IPアドレス</li><li>ログデータ</li><li>利用状況分析および製品インタラクションデータ</li>',
        pp_s2_3_meta: 'これらの情報は、サービスの安全な運用の維持、アプリのパフォーマンスの把握、バグの修正、および製品体験の向上のために使用されます。',
        pp_s3_title: '3. 情報の利用方法',
        pp_s3_desc: '私たちは、IntoDayの提供と維持、安全なログインの有効化、タスクとコンテンツの保存と表示、同期とアカウント関連機能のサポート、安定性、パフォーマンス、セキュリティの監視、および時間の経過に伴うアプリの改善のために、お客様の情報を使用します。',
        pp_s4_title: '4. 使用するサードパーティサービス',
        pp_s4_desc: '私たちは、IntoDayを運営するために信頼できるサードパーティサービスプロバイダーを使用しています。',
        pp_s4_1_title: '4.1 Supabase',
        pp_s4_1_desc: '認証、データベース、およびバックエンド関連サービスにSupabaseを使用しています。Supabaseは、サービスを提供するために必要な範囲で、お客様のアカウントデータとIntoDayに追加されたコンテンツを保存することがあります。',
        pp_s4_2_title: '4.2 Googleサインイン',
        pp_s4_2_desc: 'Googleでログインすることを選択した場合、Googleが認証プロセスを提供し、お客様が許可した権限に応じて、基本的なアカウント情報を私たちと共有することがあります。',
        pp_s4_3_title: '4.3 Vercel',
        pp_s4_3_desc: 'IntoDayのウェブサイトおよびウェブアプリのホスティングと配信にVercelを使用しています。Vercelは、ホスティング、配信、およびセキュリティの目的で、IPアドレス、ブラウザ/デバイスの詳細、およびリクエストログなどの技術情報を処理することがあります。',
        pp_s5_title: '5. 情報の共有方法',
        pp_s5_desc: '私たちは、お客様の個人情報を販売することはありません。お客様の情報は、IntoDayの運営を支援するサービスプロバイダー、法律で義務付けられている場合、またはIntoDayとそのユーザーのセキュリティ、権利、または完全性を保護するために必要な場合にのみ共有されることがあります。',
        pp_s6_title: '6. データの保持',
        pp_s6_desc: 'お客様の情報は、IntoDayの提供およびサービスの運営に必要な期間のみ保持されます。お客様がアカウントの削除またはデータの削除をリクエストした場合、法律、セキュリティ、または運用の理由で特定の情報を保持する必要がある場合を除き、合理的な期間内に個人データを削除するための合理的な努力を払います。',
        pp_s7_title: '7. データのセキュリティ',
        pp_s7_desc: '私たちは、不正アクセス、紛失、誤用、または開示からお客様の情報を保護するために、合理的な技術的および組織的措置を講じています。ただし、完全に安全なシステムはなく、絶対的なセキュリティを保証することはできません。',
        pp_s8_title: '8. お客様の選択と権利',
        pp_s8_desc: 'お住まいの地域によっては、個人データへのアクセス、訂正、または削除のリクエストを行う権利など、個人データに関する権利を有している場合があります。リクエストを行うには、以下までご連絡ください: contact.intoday@gmail.com',
        pp_s9_title: '9. 子どものプライバシー',
        pp_s9_desc: 'IntoDayは、適用法により保護者の同意なしに当該サービスを利用することが禁止されている年齢の子どもを対象としていません。私たちは、適用法に違反して子どもから個人情報を故意に収集することはありません。',
        pp_s10_title: '10. このプライバシーポリシーの変更',
        pp_s10_desc: '私たちは、このプライバシーポリシーを随時更新することがあります。重要な変更を行う場合は、このページの上部にある「発効日」を更新し、必要に応じて追加の通知を提供します。',
        pp_s11_title: '11. お問い合わせ',
        pp_s11_desc: 'ご質問、フィードバック、またはプライバシーに関するリクエストがある場合は、以下までご連絡ください: contact.intoday@gmail.com',
        ts_title: 'IntoDay 利用規約',
        ts_effective: '発効日：@2026/3/12',
        ts_intro: 'この利用規約（「本規約」）は、IntoDay（「IntoDay」、「私たち」、「私たちの」）へのアクセスおよび利用を規定するものです。',
        ts_agree: 'IntoDayにアクセスまたは利用することで、本規約に同意したことになります。同意しない場合は、IntoDayを利用しないでください。',
        ts_s1_title: '1. IntoDayについて',
        ts_s1_desc: 'IntoDayは、タスク、リマインダー、フォローアップ、および小さな予定を一日の時間ブロックに整理するためのツールです。IntoDayは現在、初期段階の製品/ベータサービスとして提供されています。一部の機能は、時間の経過とともに変更、更新、または削除される場合があります。',
        ts_s2_title: '2. 利用資格',
        ts_s2_desc: 'お客様に適用される法律の下で、法的拘束力のある合意を締結できる場合にのみ、IntoDayを利用することができます。',
        ts_s3_title: '3. お客様のアカウント',
        ts_s3_intro: 'Google認証を使用してIntoDayにサインインできます。以下の事項はお客様の責任となります：',
        ts_s3_list: '<li>アカウントのセキュリティ維持</li><li>ログイン資格情報の安全な管理</li><li>お客様のアカウントで行われるすべての活動</li>',
        ts_s3_contact: 'アカウントが無断でアクセスされたと思われる場合は、以下までご連絡ください: contact.intoday@gmail.com',
        ts_s4_title: '4. お客様のコンテンツ',
        ts_s4_desc: 'タスク、リマインダー、メモ、リンク、場所、ファイル関連の参照、およびその他のテキストを含むコンテンツをIntoDayに追加できます。お客様は、IntoDayに送信したコンテンツの所有権を保持します。お客様は、サービスの運営および提供に必要な範囲に限り、お客様のコンテンツを保存、処理、および表示するための限定的な権利を私たちに付与するものとします。お客様は、自身が追加するコンテンツ、およびそのコンテンツを利用・送信する権利を有していることを確認することについて責任を負います。',
        ts_s5_title: '5. 許容される利用方法',
        ts_s5_intro: '以下の行為を行わないことに同意するものとします：',
        ts_s5_list: '<li>不法な目的でのIntoDayの利用</li><li>有害、虐待的、権利侵害、または誤解を招くコンテンツのアップロードまたは送信</li><li>サービスのセキュリティまたは運営の妨害</li><li>自身に属さないデータへのアクセスの試み</li><li>通常の許可された範囲を超えたサービスのリバースエンジニアリング、コピー、または悪用</li>',
        ts_s5_footer: '本規約に違反したと合理的に判断した場合、アクセスを停止または終了することがあります。',
        ts_s6_title: '6. サービスの可用性',
        ts_s6_desc: 'IntoDayは「現状有姿」かつ「利用可能な範囲」で提供されます。私たちは、特にベータ段階において、いつでもサービスの一部を更新、変更、停止、または中止することがあります。IntoDayが常に利用可能であること、エラーがないこと、または中断されないことを保証するものではありません。',
        ts_s7_title: '7. ベータステータス',
        ts_s7_desc: 'IntoDayは初期段階にあるため、機能が頻繁に変更される可能性があります。一部の機能が不完全である可能性、バグや中断が発生する可能性、および製品の挙動が時間の経過とともに変化する可能性があることを理解しているものとします。フィードバックは歓迎しますが、提案を実装する義務を負うものではありません。',
        ts_s8_title: '8. プライバシー',
        ts_s8_desc: 'お客様によるIntoDayの利用は、私たちのプライバシーポリシーによっても規定されます。私たちがお客様の情報をどのように収集、利用、、および取り扱うかを理解するために、プライバシーポリシーをご確認ください。',
        ts_s9_title: '9. 終了',
        ts_s9_desc: 'いつでもIntoDayの利用を停止できます。本規約に違反した場合、サービス、ユーザー、もしくはシステムを保護する必要がある場合、またはベータ版もしくはサービスの提供を終了することを決定した場合、いつでもIntoDayへのアクセスを停止または終了することがあります。',
        ts_s10_title: '10. 免責事項',
        ts_s10_desc: 'IntoDayは生産性向上ツールに過ぎません。法的、医学的、財務的、または専門的なアドバイスを提供するものではありません。タスクの聞き逃し、データの紛失、スケジューリングの結果、またはIntoDayの利用に基づいて行われた決定について、私たちは責任を負いません。',
        ts_s11_title: '11. 責任の制限',
        ts_s11_desc: '法律で認められる最大限の範囲において、IntoDayおよびその運営者は、サービスの使用または使用不能から生じる、いかなる間接的、付随的、特別、結果的、または懲罰的な損害、あるいはデータ、利益、またはビジネス機会の損失に対しても責任を負わないものとします。',
        ts_s12_title: '12. 本規約の変更',
        ts_s12_desc: '私たちは本規約を随時更新することがあります。重要な変更を行う場合は、上記の「発効日」を更新します。更新された本規約の発効後もIntoDayの利用を継続した場合は、改訂された本規約に同意したものとみなされます。',
        ts_s13_title: '13. お問い合わせ',
        ts_s13_desc: '本規約に関するご質問は、以下までご連絡ください: contact.intoday@gmail.com',
        help_hero_label: 'サポート & リソース',
        help_hero_title: 'ヘルプ & フィードバック',
        help_hero_desc: '質問、バグ、アイデアなど、お気軽にお寄せください。IntoDayは、あなたの生活プランニングのあり方に基づいて構築されています。',
        help_card1_title: 'フィードバックを共有',
        help_card1_desc: '何が便利か、何が分かりにくいか、あるいは何が足りないか教えてください。あなたの洞察がアプリの未来を作ります。',
        help_card1_cta: 'フィードバックを送信',
        help_card2_title: 'バグを報告',
        help_card2_desc: '期待通りに動かない箇所はありますか？よりスムーズな体験を提供できるよう、修正させていただきます。',
        help_card2_cta: 'バグを報告',
        help_card3_title: 'ヘルプを求める',
        help_card3_desc: 'IntoDayの使い方や特定の機能について助けが必要ですか？丁寧に対応させていただきます。',
        help_card3_cta: 'ヘルプを見る',
        faq_title: 'よくある質問',
        faq_q1: 'IntoDayとは何ですか？',
        faq_a1: 'IntoDayは、今日やるべきことのための軽量なデイプランナーです。正確な時間を割り当てる必要はありません。',
        faq_q2: 'カレンダーとはどう違うのですか？',
        faq_a2: 'カレンダーは正確なイベントのためのものです。IntoDayは、カレンダーに入れるほどではないけれども、一日のどこかでやりたいことのための場所です。',
        faq_q3: '正確な時間を設定する必要がありますか？',
        faq_a3: 'いいえ。IntoDayは、午前、午後、夕方などの時間帯を中心に構築されているため、分刻みの計画を立てることなく整理された状態を保てます。',
        faq_q4: 'あとで移動させることはできますか？',
        faq_a4: 'はい。予定が変わった場合、最初からやり直すことなく、項目を後の時間帯や別の日に移動できます。',
        faq_q5: 'これはToDoリストアプリですか？',
        faq_a5: '正確には違います。IntoDayはToDoに「一日の居場所」を与えるので、単なるリストよりも整理されていると感じられます。',
        faq_q6: 'IntoDayは誰のためのものですか？',
        faq_a6: 'フォローアップ、リマインダー、用事、および正確な時間を必要としない小さな予定を管理するすべての人のためのものです。',
        help_contact_label: '他にお困りですか？',
        modal_optional: '（任意）',
        modal_form_error: 'エラーが発生しました。しばらくしてからもう一度お試しください。',
        modal_done: '完了',
        modal_feedback_label: 'フィードバックを共有',
        modal_feedback_title: 'どのようなお考えですか？',
        modal_feedback_sub: 'あなたのご意見がIntoDayの未来を作ります。',
        modal_feedback_q1: 'シェアしたい内容',
        modal_feedback_p1: '便利だと思うこと、わかりにくいこと、足りない機能など……',
        modal_feedback_e1: 'メッセージを入力してください。',
        modal_feedback_q2: '何をしようとしていましたか？',
        modal_feedback_p2: '例：朝のルーチンを設定中',
        modal_feedback_q3: 'メールアドレス',
        modal_feedback_p3: '追ってご連絡させていただきます',
        modal_feedback_e3: '正しいメールアドレスを入力してください。',
        modal_feedback_q4: 'スクリーンショット',
        modal_feedback_p4: '画像を添付する',
        modal_feedback_btn: 'フィードバックを送信',
        modal_feedback_s_title: 'ありがとうございます — IntoDayの改善に役立たせていただきます。',
        modal_feedback_s_desc: 'すべてのメッセージに目を通しています。メールアドレスをご記入いただいた場合は、追ってご連絡いたします。',
        modal_bug_label: 'バグを報告',
        modal_bug_title: '何が起きましたか？',
        modal_bug_sub: '詳しく教えていただけると、より迅速に修正できます。',
        modal_bug_q1: '状況',
        modal_bug_p1: '問題を詳しく教えてください……',
        modal_bug_e1: '状況を記入してください。',
        modal_bug_q2: '期待していた動作',
        modal_bug_p2: '本来どうなるべきでしたか……',
        modal_bug_e2: '期待していた動作を記入してください。',
        modal_bug_q3: 'デバイス / ブラウザ',
        modal_bug_p3: '例：iPhone, Chrome',
        modal_bug_q4: 'メールアドレス',
        modal_bug_p4: '進捗をご連絡させていただきます',
        modal_bug_q5: 'スクリーンショット',
        modal_bug_p5: '画像を添付する',
        modal_bug_btn: 'バグを報告',
        modal_bug_s_title: '承知しました。確認させていただきます。',
        modal_bug_s_desc: 'ご報告いただきありがとうございます。IntoDayをより良くするために大切に活用させていただきます。',
        modal_help_label: 'ヘルプを求める',
        modal_help_title: 'どのようにお手伝いできますか？',
        modal_help_sub: 'すべてのリクエストに個別に対応しています。また後ほど。',
        modal_help_q1: 'お困りの内容',
        modal_help_p1: '質問の内容を教えてください……',
        modal_help_e1: 'お困りの内容を記入してください。',
        modal_help_q2: 'メールアドレス',
        modal_help_p2: 'your@email.com',
        modal_help_e2: '正しいメールアドレスを入力してください。',
        modal_help_q3: 'スクリーンショット',
        modal_help_p3: '画像を添付する',
        modal_help_btn: 'ヘルプを受ける',
        modal_help_s_title: 'お問い合わせありがとうございます。',
        modal_help_s_desc: 'できるだけ早く（通常1〜2日以内）返信させていただきます。',
    },
    th: {
        flag: '🇹🇭',
        label: 'ไทย',
        nav_cta: 'เริ่มต้นฟรี',
        hero_title: 'ให้ทุกเรื่องและทุกทางเข้า<br>รวมอยู่ในวันนี้',
        hero_sub: 'จัดการวันของคุณด้วยช่วงเวลา รวมงาน ลิงก์ สถานที่ และข้อมูลไว้ในที่เดียว ลดภาระในการสลับหน้าจอไปมาเพื่อหาบริบทเดิมซ้ำๆ',
        hero_cta: 'เริ่มต้นฟรี',
        f1_label: 'จัดระเบียบตามช่วงเวลา',
        f1_title: 'ไม่ต้องเบียดเสียดในปฏิทิน และไม่ต้องกลัวลืมอีกต่อไป',
        f1_desc: 'เรื่องเล็กๆ น้อยๆ ก็วางลงในชว่งเวลาที่เหมาะสมได้ง่ายๆ',
        f2_label: 'เข้าถึงได้ทันที',
        f2_title: 'ให้ทุกรายการ นำคุณไปสู่ขั้นตอนต่อไป',
        f2_desc: 'ลิงก์ สถานที่ ไฟล์ และข้อความ — ทุกอย่างถูกบันทึกและจัดระเบียบให้อ่านง่าย พร้อมเปิดใช้ทุกเมื่อ',
        f3_label: 'เรียบง่ายที่สุด',
        f3_title: 'ทุกเรื่องของวันนี้ รวมอยู่ในหน้าเดียว',
        f3_desc: 'รวมวันของคุณไว้ที่เดียว เห็นภาพชัดเจน ทุกสิ่งที่ต้องจัดการจะอยู่ตรงหน้าคุณเสมอ',
        uc1_title: 'การติดตามงาน',
        uc1_desc: 'รวมการส่งต่องาน การติดตาม และสิ่งที่ต้องทำหลังประชุมไว้ในที่เดียว ไม่ต้องกระจัดกระจายอยู่ในโน้ต แชท หรือรายการสิ่งที่ต้องทำ',
        uc2_title: 'ระหว่างคาบเรียนและการบ้าน',
        uc2_desc: 'สิ่งที่ต้องส่ง ข้อมูลที่ต้องอ่าน ข้อความที่ต้องตอบ งานที่ต้องทำภายหลัง... ไม่ต้องกำหนดเวลา แค่วางลงในชว่งเวลาที่ใช่',
        uc3_title: 'สำหรับวันที่เปลี่ยนแปลงตลอดเวลา',
        uc3_desc: 'ไปซื้อของ ทริป เดินเล่นในเมือง หรือในวันที่ยุ่งและไม่แน่นอน — ทุกอย่างเคลื่อนย้ายได้ง่ายและแผนงานยังคงชัดเจน',
        quote: '“ไม่ต้องถูกดึงไปมาด้วยรายการงานที่กระจัดกระจาย ลิงก์ และการกำหนดเวลาที่เคร่งครัด”',
        quote_author: 'The IntoDay Philosophy',
        cta_title: 'เริ่มตั้งแต่วันนี้ ให้ทุกเรื่องมีที่ทาง และให้ทุกการกระทำมีทางเข้า!',
        cta_btn: 'เริ่มต้นฟรี',
        footer_help: 'ช่วยเหลือ / ข้อเสนอแนะ',
        footer_privacy: 'นโยบายความเป็นส่วนตัว',
        footer_terms: 'เงื่อนไขการให้บริการ',
        footer_copy: '© 2026 IntoDay. สงวนลิขสิทธิ์ทั้งหมด',
        pp_title: 'นโยบายความเป็นส่วนตัวของ IntoDay',
        pp_effective: 'วันที่มีผลบังคับใช้: @2026/3/12',
        pp_intro: 'IntoDay (“เรา”, “พวกเรา”, หรือ “ของเรา”) เคารพความเป็นส่วนตัวของคุณ นโยบายความเป็นส่วนตัวนี้อธิบายว่าข้อมูลใดบ้างที่เราเก็บรวบรวม เราใช้ข้อมูลดังกล่าวอย่างไร และคุณมีทางเลือกใดบ้างเมื่อใช้งาน IntoDay',
        pp_desc: 'IntoDay เป็นเครื่องมือสำหรับจัดระเบียบงาน การแจ้งเตือน การติดตามผล และแผนการเล็กๆ น้อยๆ ลงในบล็อกเวลาตลอดทั้งวัน',
        pp_contact_intro: 'หากคุณมีคำถามใดๆ เกี่ยวกับนโยบายความเป็นส่วนตัวนี้ คุณสามารถติดต่อเราได้ที่: contact.intoday@gmail.com',
        pp_s1_title: '1. เราคือใคร',
        pp_s1_desc: 'IntoDay เป็นผู้ให้บริการแอป IntoDay และเว็บไซต์ที่เกี่ยวข้อง หากคุณมีคำถามเกี่ยวกับความเป็นส่วนตัวหรือการจัดการข้อมูล คุณสามารถติดต่อเราได้ที่: contact.intoday@gmail.com',
        pp_s2_title: '2. ข้อมูลที่เราเก็บรวบรวม',
        pp_s2_desc: 'เราเก็บรวบรวมเฉพาะข้อมูลที่จำเป็นเพื่อให้บริการและปรับปรุง IntoDay เท่านั้น',
        pp_s2_1_title: '2.1 ข้อมูลบัญชี',
        pp_s2_1_desc: 'หากคุณลงชื่อเข้าใช้ด้วย Google เราอาจได้รับข้อมูลบัญชีพื้นฐาน เช่น:',
        pp_s2_1_list: '<li>ที่อยู่อีเมลของคุณ</li><li>ตัวระบุบัญชี Google ของคุณ</li><li>ชื่อหรือรูปโปรไฟล์ของคุณ หากระบุไว้ผ่านสิทธิ์การลงชื่อเข้าใช้ของคุณ</li>',
        pp_s2_1_meta: 'เราใช้ข้อมูลนี้เพื่อสร้างและจัดการบัญชีของคุณ และเพื่อให้คุณลงชื่อเข้าใช้ได้อย่างปลอดภัย',
        pp_s2_2_title: '2.2 เนื้อหาที่คุณเพิ่มใน IntoDay',
        pp_s2_2_desc: 'เมื่อคุณใช้ IntoDay เราอาจจัดเก็บเนื้อหาที่คุณเลือกเพิ่ม เช่น งาน การแจ้งเตือน บันทึก ลิงก์ สถานที่ การอ้างอิงที่เกี่ยวข้องกับไฟล์ และข้อความอื่นๆ ที่เกี่ยวข้องกับงานที่คุณป้อนลงในแอป',
        pp_s2_2_meta: 'เราใช้ข้อมูลนี้เพื่อจัดหาฟังก์ชันหลักของ IntoDay รวมถึงการแสดงผล การจัดระเบียบ และการซิงค์เนื้อหาของคุณ',
        pp_s2_3_title: '2.3 ข้อมูลทางเทคนิคและการใช้งาน',
        pp_s2_3_desc: 'เมื่อคุณใช้ IntoDay เราอาจรวบรวมข้อมูลทางเทคนิคบางอย่างโดยอัตโนมัติ เช่น:',
        pp_s2_3_list: '<li>ข้อมูลอุปกรณ์และเบราว์เซอร์</li><li>ที่อยู่ IP</li><li>ข้อมูลบันทึก (Log data)</li><li>ข้อมูลการวิเคราะห์การใช้งานและการโต้ตอบกับผลิตภัณฑ์</li>',
        pp_s2_3_meta: 'เราใช้ข้อมูลนี้เพื่อให้แอปทำงานได้อย่างปลอดภัย เข้าใจประสิทธิภาพของแอป แก้ไขข้อบกพร่อง และปรับปรุงประสบการณ์การใช้งานผลิตภัณฑ์',
        pp_s3_title: '3. วิธีที่เราใช้ข้อมูลของคุณ',
        pp_s3_desc: 'เราใช้ข้อมูลของคุณเพื่อจัดหาและบำรุงรักษา IntoDay ช่วยให้การลงชื่อเข้าใช้ปลอดภัย จัดเก็บและแสดงงานและเนื้อหาของคุณ สนับสนุนการซิงค์และฟังก์ชันที่เกี่ยวข้องกับบัญชี ตรวจสอบความเสถียร ประสิทธิภาพ และความปลอดภัย รวมถึงปรับปรุงแอปต่อไปในอนาคต',
        pp_s4_title: '4. บริการของบุคคลที่สามที่เราใช้',
        pp_s4_desc: 'เราใช้ผู้ให้บริการบุคคลที่สามที่เชื่อถือได้เพื่อดำเนินธุรกิจ IntoDay',
        pp_s4_1_title: '4.1 Supabase',
        pp_s4_1_desc: 'เราใช้ Supabase สำหรับการตรวจสอบสิทธิ์ ฐานข้อมูล และบริการที่เกี่ยวข้องกับส่วนหลัง (Backend) Supabase อาจจัดเก็บข้อมูลบัญชีของคุณและเนื้อหาที่คุณเพิ่มใน IntoDay ตามความจำเป็นเพื่อให้บริการ',
        pp_s4_2_title: '4.2 การลงชื่อเข้าใช้ด้วย Google',
        pp_s4_2_desc: 'หากคุณเลือกที่จะลงชื่อเข้าใช้ด้วย Google ทาง Google จะเป็นผู้ดำเนินการตามขั้นตอนการตรวจสอบสิทธิ์ และอาจแชร์ข้อมูลบัญชีพื้นฐานกับเรา ทั้งนี้ขึ้นอยู่กับสิทธิ์ที่คุณอนุญาต',
        pp_s4_3_title: '4.3 Vercel',
        pp_s4_3_desc: 'เราใช้ Vercel เพื่อโฮสต์และส่งมอบเว็บไซต์ IntoDay และเว็บแอป Vercel อาจประมวลผลข้อมูลทางเทคนิค เช่น ที่อยู่ IP รายละเอียดเบราว์เซอร์/อุปกรณ์ และบันทึกคำขอ เพื่อวัตถุประสงค์ในการโฮสต์ การส่งมอบ และความปลอดภัย',
        pp_s5_title: '5. วิธีที่เราแบ่งปันข้อมูล',
        pp_s5_desc: 'เราไม่ขายข้อมูลส่วนบุคคลของคุณ เราอาจแบ่งปันข้อมูลของคุณกับผู้ให้บริการที่ช่วยเราดำเนินธุรกิจ IntoDay เมื่อกฎหมายกำหนด หรือเมื่อจำเป็นเพื่อปกป้องความปลอดภัย สิทธิ์ หรือความสมบูรณ์ของ IntoDay และผู้ใช้เท่านั้น',
        pp_s6_title: '6. การเก็บรักษาข้อมูล',
        pp_s6_desc: 'เราจะเก็บข้อมูลของคุณไว้ตราบเท่าที่จำเป็นเพื่อให้บริการ IntoDay และดำเนินธุรกิจเท่านั้น หากคุณลบบัญชีของคุณหรือร้องขอการลบข้อมูล เราจะใช้ความพยายามตามสมควรในการลบข้อมูลส่วนบุคคลของคุณภายในระยะเวลาที่เหมาะสม เว้นแต่เราจำเป็นต้องเก็บข้อมูลบางอย่างไว้ด้วยเหตุผลทางกฎหมาย ความปลอดภัย หรือการดำเนินงาน',
        pp_s7_title: '7. ความปลอดภัยของข้อมูล',
        pp_s7_desc: 'เราใช้มาตรการทางเทคนิคและมาตรการขององค์กรตามสมควรเพื่อปกป้องข้อมูลของคุณจากการเข้าถึงโดยไม่ได้รับอนุญาต การสูญหาย การใช้ผิดวัตถุประสงค์ หรือการเปิดเผย อย่างไรก็ตาม ไม่มีระบบใดที่ปลอดภัยอย่างสมบูรณ์ และเราไม่สามารถรับประกันความปลอดภัยที่สมบูรณ์ได้',
        pp_s8_title: '8. ทางเลือกและสิทธิ์ของคุณ',
        pp_s8_desc: 'สิทธิ์เกี่ยวกับข้อมูลส่วนบุคคลของคุณอาจขึ้นอยู่กับสถานที่ตั้งของคุณ รวมถึงสิทธิ์ในการเข้าถึง แก้ไข หรือร้องขอการลบข้อมูลของคุณ หากต้องการส่งคำขอ โปรดติดต่อเราที่: contact.intoday@gmail.com',
        pp_s9_title: '9. ความเป็นส่วนตัวของเด็ก',
        pp_s9_desc: 'IntoDay ไม่ได้มีไว้สำหรับเด็กที่อายุต่ำกว่าที่กฎหมายกำหนดให้ใช้บริการดังกล่าวได้โดยไม่ได้รับความยินยอมจากผู้ปกครอง เราไม่ได้เจตนาเก็บรวบรวมข้อมูลส่วนบุคคลจากเด็กโดยเป็นการละเมิดกฎหมายที่เกี่ยวข้อง',
        pp_s10_title: '10. การเปลี่ยนแปลงนโยบายความเป็นส่วนตัวนี้',
        pp_s10_desc: 'เราอาจอัปเดตนโยบายความเป็นส่วนตัวนี้เป็นครั้งคราว หากเราทำการเปลี่ยนแปลงที่เป็นสาระสำคัญ เราจะอัปเดต "วันที่มีผลบังคับใช้" ที่ด้านบนของหน้านี้ และหากเหมาะสม จะมีการแจ้งเตือนเพิ่มเติม',
        pp_s11_title: '11. ติดต่อเรา',
        pp_s11_desc: 'หากคุณมีคำถาม ข้อเสนอแนะ หรือคำขอเกี่ยวกับความเป็นส่วนตัว คุณสามารถติดต่อเราได้ที่: contact.intoday@gmail.com',
        ts_title: 'เงื่อนไขการให้บริการของ IntoDay',
        ts_effective: 'วันที่มีผลบังคับใช้: @2026/3/12',
        ts_intro: 'เงื่อนไขการให้บริการเหล่านี้ (“เงื่อนไข”) ควบคุมการเข้าถึงและการใช้งาน IntoDay ของคุณ (“IntoDay”, “เรา”, “พวกเรา”, หรือ “ของเรา”)',
        ts_agree: 'การเข้าถึงหรือใช้งาน IntoDay แสดงว่าคุณตกลงตามเงื่อนไขเหล่านี้ หากคุณไม่ตกลง โปรดอย่าใช้งาน IntoDay',
        ts_s1_title: '1. เกี่ยวกับ IntoDay',
        ts_s1_desc: 'IntoDay เป็นเครื่องมือสำหรับจัดระเบียบงาน การแจ้งเตือน การติดตามผล และแผนการเล็กๆ น้อยๆ ลงในบล็อกเวลาตลอดทั้งวัน ปัจจุบัน IntoDay ให้บริการในรูปแบบของผลิตภัณฑ์รุ่นแรกเริ่ม / บริการแบบเบต้า คุณลักษณะบางอย่างอาจมีการเปลี่ยนแปลง อัปเดต หรือถูกลบออกเมื่อเวลาผ่านไป',
        ts_s2_title: '2. คุณสมบัติของผู้ใช้งาน',
        ts_s2_desc: 'คุณอาจใช้งาน IntoDay ได้เฉพาะในกรณีที่คุณสามารถทำข้อตกลงที่มีผลผูกพันทางกฎหมายภายใต้กฎหมายที่บังคับใช้กับคุณเท่านั้น',
        ts_s3_title: '3. บัญชีของคุณ',
        ts_s3_intro: 'คุณสามารถลงชื่อเข้าใช้ IntoDay โดยใช้การตรวจสอบสิทธิ์ของ Google คุณมีหน้าที่รับผิดชอบในเรื่องดังต่อไปนี้:',
        ts_s3_list: '<li>การรักษาความปลอดภัยของบัญชีของคุณ</li><li>การเก็บรักษาข้อมูลการลงชื่อเข้าใช้ของคุณให้ปลอดภัย</li><li>กิจกรรมทั้งหมดที่เกิดขึ้นภายใต้บัญชีของคุณ</li>',
        ts_s3_contact: 'หากคุณเชื่อว่าบัญชีของคุณถูกเข้าถึงโดยไม่ได้รับอนุญาต โปรดติดต่อเราที่: contact.intoday@gmail.com',
        ts_s4_title: '4. เนื้อหาของคุณ',
        ts_s4_desc: 'คุณสามารถเพิ่มเนื้อหาลงใน IntoDay ได้ ซึ่งรวมถึงงาน การแจ้งเตือน บันทึก ลิงก์ สถานที่ การอ้างอิงที่เกี่ยวข้องกับไฟล์ และข้อความอื่นๆ คุณยังคงเป็นเจ้าของเนื้อหาที่คุณส่งไปยัง IntoDay คุณมอบสิทธิ์ที่จำกัดให้เราในการจัดเก็บ ประมวลผล และแสดงเนื้อหาของคุณตามความจำเป็นเพื่อดำเนินการและให้บริการเท่านั้น คุณมีหน้าที่รับผิดชอบต่อเนื้อหาที่คุณเพิ่มและต้องมั่นใจว่าคุณมีสิทธิ์ในการใช้งานและส่งเนื้อหานั้น',
        ts_s5_title: '5. การใช้งานที่ยอมรับได้',
        ts_s5_intro: 'คุณตกลงที่จะไม่:',
        ts_s5_list: '<li>ใช้งาน IntoDay เพื่อวัตถุประสงค์ที่ผิดกฎหมาย</li><li>อัปโหลดหรือส่งเนื้อหาที่เป็นอันตราย ละเมิดสิทธิ์ ล่วงละเมิด หรือทำให้เข้าใจผิด</li><li>รบกวนความปลอดภัยหรือการดำเนินธุรกิจของบริการ</li><li>พยายามเข้าถึงข้อมูลที่ไม่ใช่ของคุณ</li><li>ทำวิศวกรรมย้อนกลับ (Reverse engineer) คัดลอก หรือนำบริการไปใช้ในทางที่ผิดนอกเหนือจากการใช้งานปกติที่ได้รับอนุญาต</li>',
        ts_s5_footer: 'เราอาจระงับหรือยกเลิกการเข้าถึงหากเราเชื่อตามสมควรว่าคุณได้ละเมิดเงื่อนไขเหล่านี้',
        ts_s6_title: '6. ความพร้อมใช้งานของบริการ',
        ts_s6_desc: 'IntoDay ให้บริการตามสภาพที่เป็นอยู่ (“as is”) และตามความพร้อมจำหน่าย (“as available”) เราอาจอัปเดต เปลี่ยนแปลง ระงับ หรือหยุดบางส่วนของบริการเมื่อใดก็ได้ โดยเฉพาะในช่วงเบต้า เราไม่รับประกันว่า IntoDay จะพร้อมใช้งานเสมอไป ไม่มีข้อผิดพลาด หรือไม่ถูกขัดจังหวะ',
        ts_s7_title: '7. สถานะเบต้า',
        ts_s7_desc: 'เนื่องจาก IntoDay อยู่ในช่วงเริ่มต้น คุณลักษณะต่างๆ อาจเปลี่ยนแปลงบ่อยครั้ง คุณเข้าใจว่าคุณลักษณะบางอย่างอาจไม่สมบูรณ์ อาจเกิดข้อผิดพลาดหรือการขัดจังหวะ และพฤติกรรมของผลิตภัณฑ์อาจเปลี่ยนแปลงไปเมื่อเวลาผ่านไป เรายินดีรับข้อเสนอแนะ แต่เราไม่มีภาระผูกพันที่จะต้องดำเนินการตามข้อเสนอแนะใดๆ',
        ts_s8_title: '8. ความเป็นส่วนตัว',
        ts_s8_desc: 'การใช้งาน IntoDay ของคุณยังอยู่ภายใต้นโยบายความเป็นส่วนตัวของเราด้วย โปรดตรวจสอบนโยบายความเป็นส่วนตัวเพื่อทำความเข้าใจว่าเราเก็บรวบรวม ใช้ และจัดการข้อมูลของคุณอย่างไร',
        ts_s9_title: '9. การยกเลิกการใช้งาน',
        ts_s9_desc: 'คุณสามารถหยุดใช้งาน IntoDay ได้ทุกเมื่อ เราอาจระงับหรือยกเลิกการเข้าถึง IntoDay ของคุณได้ทุกเมื่อหากคุณละเมิดเงื่อนไขเหล่านี้ หากเราจำเป็นต้องปกป้องบริการ ผู้ใช้ หรือระบบของเรา หรือหากเราตัดสินใจที่จะยุติช่วงเบต้าหรือบริการ',
        ts_s10_title: '10. การปฏิเสธความรับผิดชอบ',
        ts_s10_desc: 'IntoDay เป็นเครื่องมือเพื่อประสิทธิภาพการทำงานเท่านั้น ไม่ได้ให้คำแนะนำด้านกฎหมาย การแพทย์ การเงิน หรือวิชาชีพ เราไม่รับผิดชอบต่องานที่พลาดไป ข้อมูลที่สูญหาย ผลลัพธ์ของการจัดกำหนดการ หรือการตัดสินใจใดๆ ที่เกิดขึ้นจากการใช้งาน IntoDay',
        ts_s11_title: '11. ข้อจำกัดความรับผิด',
        ts_s11_desc: 'ตามขอบเขตสูงสุดที่กฎหมายอนุญาต IntoDay และผู้บริหารจะไม่รับผิดชอบต่อความเสียหายทางอ้อม ความเสียหายที่เกิดขึ้นโดยบังเอิญ ความเสียหายพิเศษ ความเสียหายที่เป็นผลสืบเนื่อง หรือความเสียหายเชิงลงโทษ หรือการสูญหายของข้อมูล กำไร หรือโอกาสทางธุรกิจที่เป็นผลมาจากการใช้งานหรือการไม่สามารถใช้งานบริการได้',
        ts_s12_title: '12. การเปลี่ยนแปลงเงื่อนไขเหล่านี้',
        ts_s12_desc: 'เราอาจอัปเดตเงื่อนไขเหล่านี้เป็นครั้งคราว หากเราทำการเปลี่ยนแปลงที่เป็นสาระสำคัญ เราจะอัปเดตวันที่มีผลบังคับใช้ข้างต้น การที่คุณใช้งาน IntoDay ต่อไปหลังจากเงื่อนไขที่อัปเดตมีผลบังคับใช้ แสดงว่าคุณตกลงตามเงื่อนไขที่แก้ไขแล้ว',
        ts_s13_title: '13. ติดต่อเรา',
        ts_s13_desc: 'หากคุณมีคำถามเกี่ยวกับเงื่อนไขเหล่านี้ คุณสามารถติดต่อเราได้ที่: contact.intoday@gmail.com',
        help_hero_label: 'การสนับสนุนและทรัพยากร',
        help_hero_title: 'ช่วยเหลือและเสนอแนะ',
        help_hero_desc: 'คำถาม ข้อบกพร่อง หรือไอเดีย — เราอยากได้ยินจากคุณ เราสร้าง IntoDay ตามลักษณะการวางแผนชีวิตของคุณ',
        help_card1_title: 'แบ่งปันข้อเสนอแนะ',
        help_card1_desc: 'บอกเราว่าอะไรที่คุณรู้สึกว่ามีประโยชน์ น่าสับสน หรือขาดหายไป ข้อมูลเชิงลึกของคุณช่วยกำหนดอนาคตของแอป',
        help_card1_cta: 'ส่งข้อเสนอแนะ',
        help_card2_title: 'รายงานข้อบกพร่อง',
        help_card2_desc: 'มีบางอย่างไม่ทำงานตามที่คาดไว้ใช่ไหม? แจ้งให้เราทราบเพื่อให้เราแก้ไขและทำให้ประสบการณ์ของคุณราบรื่นขึ้น',
        help_card2_cta: 'รายงานบั๊ก',
        help_card3_title: 'สอบถามความช่วยเหลือ',
        help_card3_desc: 'ต้องการความช่วยเหลือในการใช้งาน IntoDay หรือทำความเข้าใจคุณลักษณะเฉพาะใช่ไหม? เราพร้อมช่วยเหลือคุณ',
        help_card3_cta: 'ขอความช่วยเหลือ',
        faq_title: 'คำถามที่พบบ่อย',
        faq_q1: 'IntoDay คืออะไร?',
        faq_a1: 'IntoDay คือเครื่องมือวางแผนรายวันที่ใช้งานง่าย สำหรับสิ่งที่คุณต้องทำในวันนี้ โดยไม่ต้องระบุเวลาที่แน่นอน',
        faq_q2: 'แตกต่างจากปฏิทินอย่างไร?',
        faq_a2: 'ปฏิทินมีไว้สำหรับเหตุการณ์ที่ระบุเวลาแน่นอน IntoDay มีไว้สำหรับสิ่งที่คุณต้องการใส่ลงในวันของคุณโดยไม่ต้องการให้เป็นรายการในปฏิทิน',
        faq_q3: 'ฉันต้องระบุเวลาที่แน่นอนหรือไม่?',
        faq_a3: 'ไม่จำเป็น IntoDay สร้างขึ้นตามช่วงเวลาต่างๆ เช่น เช้า บ่าย และเย็น — เพื่อให้คุณจัดระเบียบได้โดยไม่ต้องวางแผนทุกอย่างเป็นรายนาที',
        faq_q4: 'ฉันสามารถเลื่อนรายการไปภายหลังได้ไหม?',
        faq_a4: 'ได้ หากแผนเปลี่ยน คุณสามารถย้ายรายการไปยังช่วงเวลาที่ช้าลงหรือวันอื่นได้โดยไม่ต้องเริ่มต้นใหม่',
        faq_q5: 'นี่คือแอปรายการสิ่งที่ต้องทำใช่ไหม?',
        faq_a5: 'ไม่เชิง IntoDay ให้ "ที่อยู่" สำหรับรายการสิ่งที่ต้องทำของคุณในวันนั้น ทำให้รู้สึกเป็นระเบียบมากกว่ารายการแบบง่ายๆ',
        faq_q6: 'IntoDay เหมาะกับใคร?',
        faq_a6: 'เหมาะสำหรับทุกคนที่ต้องจัดการการติดตามผล การแจ้งเตือน ธุระ และแผนการเล็กๆ น้อยๆ ที่ไม่ต้องระบุเวลาแน่นอน',
        help_contact_label: 'ยังต้องการความช่วยเหลือใช่ไหม?',
        modal_optional: 'ระบุหรือไม่ก็ได้',
        modal_form_error: 'เกิดบางอย่างผิดพลาด โปรดลองอีกครั้งในภายหลัง',
        modal_done: 'เสร็จสิ้น',
        modal_feedback_label: 'เสนอแนะติชม',
        modal_feedback_title: 'คุณกำลังนึกถึงอะไรอยู่?',
        modal_feedback_sub: 'ความคิดเห็นของคุณช่วยเราสร้างอนาคตของ IntoDay',
        modal_feedback_q1: 'คุณต้องการจะแชร์อะไร?',
        modal_feedback_p1: 'บอกเราว่าสิ่งไหนที่มีประโยชน์ สับสน หรือขาดหายไป…',
        modal_feedback_e1: 'โปรดแชร์ความคิดเห็นกับเรา',
        modal_feedback_q2: 'คุณกำลังพยายามทำอะไร?',
        modal_feedback_p2: 'เช่น การตั้งค่ากิจวัตรตอนเช้า',
        modal_feedback_q3: 'อีเมลของคุณ',
        modal_feedback_p3: 'เพื่อให้เราติดต่อกลับได้',
        modal_feedback_e3: 'โปรดกรอกอีเมลที่ถูกต้อง',
        modal_feedback_q4: 'ภาพหน้าจอ',
        modal_feedback_p4: 'แนบภาพหน้าจอ',
        modal_feedback_btn: 'ส่งข้อเสนอแนะ',
        modal_feedback_s_title: 'ขอบคุณ — สิ่งนี้ช่วยเราปรับปรุง IntoDay ได้มาก',
        modal_feedback_s_desc: 'เราอ่านทุกข้อความ หากคุณทิ้งอีเมลไว้ เราจะติดต่อกลับเร็วๆ นี้',
        modal_bug_label: 'รายงานบั๊ก',
        modal_bug_title: 'มีอะไรผิดพลาด?',
        modal_bug_sub: 'ยิ่งได้รายละเอียดมากเท่าไหร่ เราก็จะแก้ไขได้เร็วขึ้นเท่านั้น',
        modal_bug_q1: 'เกิดอะไรขึ้น?',
        modal_bug_p1: 'อธิบายปัญหา…',
        modal_bug_e1: 'โปรดอธิบายสิ่งที่เกิดขึ้น',
        modal_bug_q2: 'คุณคาดหวังอะไร?',
        modal_bug_p2: 'สิ่งที่ควรเกิดขึ้นคือ…',
        modal_bug_e2: 'โปรดอธิบายสิ่งที่คุณคาดหวัง',
        modal_bug_q3: 'อุปกรณ์ / เบราว์เซอร์',
        modal_bug_p3: 'เช่น iPhone, Chrome',
        modal_bug_q4: 'อีเมลของคุณ',
        modal_bug_p4: 'เพื่อให้เราแจ้งความคืบหน้าให้คุณทราบ',
        modal_bug_q5: 'ภาพหน้าจอ',
        modal_bug_p5: 'แนบภาพหน้าจอ',
        modal_bug_btn: 'รายงานบั๊ก',
        modal_bug_s_title: 'ได้รับแล้ว — เราจะรีบเข้าไปดูแล',
        modal_bug_s_desc: 'ขอบคุณที่สละเวลาแจ้งให้เราทราบ สิ่งนี้ช่วยให้ IntoDay ดีขึ้นจริงๆ',
        modal_help_label: 'ขอความช่วยเหลือ',
        modal_help_title: 'เราจะช่วยคุณได้อย่างไร?',
        modal_help_sub: 'เราตอบกลับทุกคำขอเป็นการส่วนตัว แล้วคุยกันนะ',
        modal_help_q1: 'คุณต้องการความช่วยเหลือในเรื่องใด?',
        modal_help_p1: 'อธิบายคำถามของคุณ…',
        modal_help_e1: 'โปรดบอกเราว่าคุณต้องการความช่วยเหลือในเรื่องใด',
        modal_help_q2: 'อีเมลของคุณ',
        modal_help_p2: 'อีเมล@ของคุณ.com',
        modal_help_e2: 'โปรดกรอกอีเมลที่ถูกต้อง',
        modal_help_q3: 'ภาพหน้าจอ',
        modal_help_p3: 'แนบภาพหน้าจอ',
        modal_help_btn: 'ขอความช่วยเหลือ',
        modal_help_s_title: 'ขอบคุณสำหรับการติดต่อเรา',
        modal_help_s_desc: 'เราจะตอบกลับอีเมลของคุณโดยเร็วที่สุด — โดยปกติจะภายใน 1-2 วัน',
    },
};

let currentLang = 'en';

function applyLanguage(lang) {
    if (!translations[lang]) return; // Check if translation exists
    const t = translations[lang];

    // Update all data-i18n elements
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key] !== undefined) {
            el.innerHTML = t[key];
        }
    });

    // Update all data-i18n-placeholder elements
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (t[key] !== undefined) {
            el.setAttribute('placeholder', t[key]);
        }
    });

    // Update lang button display
    document.getElementById('lang-label').textContent = t.label;

    // Update html lang attribute
    document.documentElement.lang = lang;

    currentLang = lang;
    localStorage.setItem('intoday_lang', lang); // Save language preference
    closeLangMenu();
}

function closeLangMenu() {
    const menu = document.getElementById('lang-menu');
    const btn = document.getElementById('lang-btn');
    menu.classList.remove('open');
    btn.setAttribute('aria-expanded', 'false');
}

function toggleLangMenu() {
    const menu = document.getElementById('lang-menu');
    const btn = document.getElementById('lang-btn');
    const isOpen = menu.classList.contains('open');
    menu.classList.toggle('open');
    btn.setAttribute('aria-expanded', String(!isOpen));
}

// Theme Switcher Logic
function initTheme() {
    const themeBtn = document.getElementById('theme-btn');
    const themeIcon = document.getElementById('theme-icon');
    const savedTheme = localStorage.getItem('theme');
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    
    function setIcon(isDark) {
        if(themeIcon) {
            themeIcon.src = isDark ? 'assets/sun.png' : 'assets/moon.png';
        }
    }

    // Set initial state
    const isInitialDark = savedTheme === 'dark' || (!savedTheme && prefersDark);
    if (isInitialDark) {
        document.documentElement.classList.add('dark');
    } else {
        document.documentElement.classList.remove('dark');
    }
    setIcon(isInitialDark);

    // Handle toggle click
    if (themeBtn) {
        themeBtn.addEventListener('click', () => {
            const isDark = document.documentElement.classList.contains('dark');
            if (isDark) {
                document.documentElement.classList.remove('dark');
                localStorage.setItem('theme', 'light');
                setIcon(false);
            } else {
                document.documentElement.classList.add('dark');
                localStorage.setItem('theme', 'dark');
                setIcon(true);
            }
        });
    }
}

// Header Scroll Logic
function initHeaderScroll() {
    const header = document.querySelector('header');
    if (!header) return;

    window.addEventListener('scroll', () => {
        if (window.scrollY > 10) {
            header.classList.add('border-brand-border/40', 'dark:border-dark-border/40');
            header.classList.remove('border-transparent');
        } else {
            header.classList.remove('border-brand-border/40', 'dark:border-dark-border/40');
            header.classList.add('border-transparent');
        }
    });
}

// Scroll Reveal Logic
function initScrollReveal() {
    const observerOptions = {
        root: null,
        rootMargin: '0px',
        threshold: 0.1
    };

    const revealObserver = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                const el = entry.target;
                const revealClass = el.getAttribute('data-reveal');
                if (revealClass) {
                    // Split by spaces to support multiple classes (though usually just one)
                    revealClass.split(' ').forEach(cls => {
                        if (cls) el.classList.add(cls);
                    });
                }
                revealObserver.unobserve(el);
            }
        });
    }, observerOptions);

    document.querySelectorAll('[data-reveal]').forEach(el => {
        revealObserver.observe(el);
    });
}

// Init
document.addEventListener('DOMContentLoaded', () => {
    // Initialize Theme
    initTheme();

    // Initialize Header Scroll
    initHeaderScroll();

    // Initialize Scroll Reveal
    initScrollReveal();

    // Toggle dropdown
    document.getElementById('lang-btn').addEventListener('click', (e) => {
        e.stopPropagation();
        toggleLangMenu();
    });

    // Select language
    document.querySelectorAll('.lang-option').forEach(btn => {
        btn.addEventListener('click', () => {
            applyLanguage(btn.getAttribute('data-lang'));
        });
    });

    // Close on outside click
    document.addEventListener('click', () => closeLangMenu());
 
    // Check saved language or default to English
    const savedLang = localStorage.getItem('intoday_lang');
    if (savedLang && translations[savedLang]) {
        applyLanguage(savedLang);
    }
});
